import {
  PartyMember,
  CombatSkill,
  SkillNode,
  CraftingRecipe,
  MonsterCodexEntry,
  QuestLogEntry,
  TurnBasedEnemy,
  AudioVisualSettings,
} from '../types/game';

export const DEFAULT_COMBAT_SKILLS: Record<string, CombatSkill> = {
  // Valen
  silver_slash: {
    id: 'silver_slash',
    name: 'Tebasan Perak',
    description: 'Serangan pedang perak presisi yang menembus armor musuh.',
    element: 'Physical',
    costMp: 0,
    power: 28,
    target: 'single_enemy',
    icon: 'Sword',
  },
  holy_fire_shot: {
    id: 'holy_fire_shot',
    name: 'Peluru Api Suci',
    description: 'Menembakkan peluru suci yang membakar target dan mengeksploitasi kelemahan Fire.',
    element: 'Fire',
    costMp: 12,
    power: 45,
    target: 'single_enemy',
    statusEffect: 'Bleed',
    icon: 'Flame',
  },
  blood_rend: {
    id: 'blood_rend',
    name: 'Mantra Pemotong Darah',
    description: 'Tebasan menyilang yang memberikan pendarahan berlanjut pada semua musuh.',
    element: 'Physical',
    costMp: 20,
    power: 36,
    target: 'all_enemies',
    statusEffect: 'Bleed',
    icon: 'Zap',
  },
  valen_ultimate: {
    id: 'valen_ultimate',
    name: 'Crimson Judgement',
    description: 'Jurus pamungkas pemburu: Hujan pedang berapi yang menghancurkan Stagger musuh secara instan!',
    element: 'Fire',
    costMp: 0,
    power: 120,
    target: 'all_enemies',
    icon: 'Sparkles',
    isUltimate: true,
  },
  // Genevieve
  healing_grace: {
    id: 'healing_grace',
    name: 'Cahaya Penyembuh',
    description: 'Memulihkan HP target kawan secara signifikan dan memberikan efek regenerasi.',
    element: 'Holy',
    costMp: 15,
    power: 50,
    target: 'single_ally',
    statusEffect: 'Regen',
    icon: 'Heart',
  },
  sanctuary_shield: {
    id: 'sanctuary_shield',
    name: 'Perisai Suci Katedral',
    description: 'Membungkus seluruh kawan dengan perisai suci yang menyerap damage.',
    element: 'Holy',
    costMp: 22,
    power: 0,
    target: 'all_allies',
    statusEffect: 'Shield',
    icon: 'Shield',
  },
  sunbeam_smite: {
    id: 'sunbeam_smite',
    name: 'Hukuman Matahari Fajar',
    description: 'Pilar cahaya fajar suci yang memusnahkan undead dan meretakkan pertahanan.',
    element: 'Holy',
    costMp: 18,
    power: 42,
    target: 'single_enemy',
    icon: 'Sun',
  },
  genevieve_ultimate: {
    id: 'genevieve_ultimate',
    name: 'Angelic Sanctuary',
    description: 'Doa agung para malaikat: Memulihkan total seluruh tim, membersihkan kutukan, dan meningkatkan pertahanan!',
    element: 'Holy',
    costMp: 0,
    power: 100,
    target: 'all_allies',
    icon: 'Sparkles',
    isUltimate: true,
  },
  // Celeste
  frost_lance: {
    id: 'frost_lance',
    name: 'Tombak Es Beku',
    description: 'Tombak es glasial bertekanan tinggi yang berpeluang membekukan musuh.',
    element: 'Ice',
    costMp: 14,
    power: 40,
    target: 'single_enemy',
    statusEffect: 'Stun',
    icon: 'Snowflake',
  },
  abyssal_miasma: {
    id: 'abyssal_miasma',
    name: 'Kabut Kegelapan Racun',
    description: 'Melepaskan kabut kutukan kegelapan yang meracuni musuh setiap giliran.',
    element: 'Dark',
    costMp: 20,
    power: 32,
    target: 'all_enemies',
    statusEffect: 'Poison',
    icon: 'Skull',
  },
  celeste_ultimate: {
    id: 'celeste_ultimate',
    name: 'Abyssal Eclipse',
    description: 'Gerhana kegelapan abadi yang membekukan ruang dan memberikan damage elemental dahsyat ke semua musuh!',
    element: 'Dark',
    costMp: 0,
    power: 135,
    target: 'all_enemies',
    icon: 'Sparkles',
    isUltimate: true,
  },
};

export const DEFAULT_PARTY_MEMBERS: PartyMember[] = [
  {
    id: 'valen',
    name: 'Valen',
    title: 'Pemburu Vampir Terkutuk',
    avatar: 'hunter',
    role: 'DPS',
    level: 5,
    hp: 120,
    maxHp: 120,
    mp: 45,
    maxMp: 45,
    attack: 34,
    defense: 12,
    speed: 18,
    element: 'Fire',
    ultimateGauge: 35,
    statusEffects: [],
    skills: [
      DEFAULT_COMBAT_SKILLS.silver_slash,
      DEFAULT_COMBAT_SKILLS.holy_fire_shot,
      DEFAULT_COMBAT_SKILLS.blood_rend,
      DEFAULT_COMBAT_SKILLS.valen_ultimate,
    ],
  },
  {
    id: 'genevieve',
    name: 'Genevieve',
    title: 'Biarawati Cahaya Fajar',
    avatar: 'sister',
    role: 'Healer',
    level: 5,
    hp: 95,
    maxHp: 95,
    mp: 75,
    maxMp: 75,
    attack: 16,
    defense: 15,
    speed: 14,
    element: 'Holy',
    ultimateGauge: 45,
    statusEffects: [],
    skills: [
      DEFAULT_COMBAT_SKILLS.healing_grace,
      DEFAULT_COMBAT_SKILLS.sanctuary_shield,
      DEFAULT_COMBAT_SKILLS.sunbeam_smite,
      DEFAULT_COMBAT_SKILLS.genevieve_ultimate,
    ],
  },
  {
    id: 'celeste',
    name: 'Celeste',
    title: 'Penyihir Bayangan & Es',
    avatar: 'sorceress',
    role: 'Mage',
    level: 5,
    hp: 85,
    maxHp: 85,
    mp: 90,
    maxMp: 90,
    attack: 42,
    defense: 8,
    speed: 21,
    element: 'Dark',
    ultimateGauge: 20,
    statusEffects: [],
    skills: [
      DEFAULT_COMBAT_SKILLS.frost_lance,
      DEFAULT_COMBAT_SKILLS.abyssal_miasma,
      DEFAULT_COMBAT_SKILLS.celeste_ultimate,
    ],
  },
];

export const DEFAULT_SKILL_TREE_NODES: SkillNode[] = [
  // Valen Nodes
  {
    id: 'valen_atk_1',
    name: 'Asah Pedang Perak',
    characterId: 'valen',
    branch: 'Offense',
    tier: 1,
    costSp: 1,
    unlocked: true,
    icon: 'Sword',
    description: '+6 Kekuatan Serangan (ATK) dasar untuk Valen.',
    statBonus: { atk: 6 },
  },
  {
    id: 'valen_fire_infusion',
    name: 'Infus Api Suci',
    characterId: 'valen',
    branch: 'Offense',
    tier: 2,
    costSp: 2,
    unlocked: false,
    requiresNodeId: 'valen_atk_1',
    icon: 'Flame',
    description: 'Serangan tebasan biasa kini berpeluang membakar musuh (Bleed effect).',
    statBonus: { atk: 10 },
  },
  {
    id: 'valen_def_1',
    name: 'Armor Kulit Serigala',
    characterId: 'valen',
    branch: 'Defense',
    tier: 1,
    costSp: 1,
    unlocked: false,
    icon: 'Shield',
    description: '+20 Max HP dan +4 Pertahanan (DEF).',
    statBonus: { maxHp: 20, def: 4 },
  },
  {
    id: 'valen_dash_master',
    name: 'Langkah Bayangan Fajar',
    characterId: 'valen',
    branch: 'Utility',
    tier: 1,
    costSp: 1,
    unlocked: false,
    icon: 'Zap',
    description: '+5 Kecepatan Giliran (SPD) di pertarungan turn-based.',
    statBonus: { spd: 5 },
  },
  // Genevieve Nodes
  {
    id: 'gen_heal_boost',
    name: 'Iman Tak Tergoyahkan',
    characterId: 'genevieve',
    branch: 'Defense',
    tier: 1,
    costSp: 1,
    unlocked: true,
    icon: 'Heart',
    description: 'Meningkatkan efektivitas mantra penyembuhan sebesar 25%.',
    statBonus: { maxHp: 25 },
  },
  {
    id: 'gen_holy_radiance',
    name: 'Aura Kesucian',
    characterId: 'genevieve',
    branch: 'Offense',
    tier: 2,
    costSp: 2,
    unlocked: false,
    requiresNodeId: 'gen_heal_boost',
    icon: 'Sun',
    description: '+12 Serangan Holy terhadap musuh tipe undead dan vampire.',
    statBonus: { atk: 12 },
  },
  // Celeste Nodes
  {
    id: 'cel_mana_flow',
    name: 'Aliran Mana Kosmik',
    characterId: 'celeste',
    branch: 'Utility',
    tier: 1,
    costSp: 1,
    unlocked: true,
    icon: 'Sparkles',
    description: '+15 Serangan Sihir dan pengurangan konsumsi MP 20%.',
    statBonus: { atk: 15 },
  },
  {
    id: 'cel_permafrost',
    name: 'Napas Es Abadi',
    characterId: 'celeste',
    branch: 'Offense',
    tier: 2,
    costSp: 2,
    unlocked: false,
    requiresNodeId: 'cel_mana_flow',
    icon: 'Snowflake',
    description: 'Peluang Stun mantra es meningkat menjadi 60% dan +8 Kecepatan.',
    statBonus: { spd: 8 },
  },
];

export const DEFAULT_CRAFTING_RECIPES: CraftingRecipe[] = [
  {
    id: 'craft_gothic_bone_blade',
    resultItem: {
      id: 'gothic_bone_blade',
      name: 'Pedang Tulang Katedral (Gothic Bone Blade)',
      description: 'Pedang tempaan dari serpihan tengkorak terkutuk. Menimbulkan luka dalam dan bonus damage Physical.',
      icon: '⚔️',
      category: 'equipment',
      equip_slot: 'weapon',
      attack_bonus: 26,
      defense_bonus: 2,
      heal_amount: 0,
      count: 1,
      is_stackable: false,
      value: 190,
      rarity: 'rare',
      color: '#e2e8f0',
    },
    requiredMaterials: [
      { itemId: 'bone_fragment', name: 'Fragmen Tulang Kuno', icon: '🦴', count: 3 },
      { itemId: 'silver_rapier', name: 'Rapier Perak', icon: '🗡️', count: 1 },
    ],
    requiredGold: 60,
    description: 'Tempaan senjata tajam berselimut aura dingin kuburan.',
  },
  {
    id: 'craft_blood_aegis',
    resultItem: {
      id: 'blood_aegis_armor',
      name: 'Zirah Plat Darah Kegelapan',
      description: 'Armor berat berpaku perak yang disiram darah bangsawan vampir untuk ketahanan maksimal.',
      icon: '🛡️',
      category: 'equipment',
      equip_slot: 'armor',
      attack_bonus: 5,
      defense_bonus: 18,
      hp_bonus: 45,
      heal_amount: 0,
      count: 1,
      is_stackable: false,
      value: 280,
      rarity: 'epic',
      color: '#dc2626',
    },
    requiredMaterials: [
      { itemId: 'bone_fragment', name: 'Fragmen Tulang Kuno', icon: '🦴', count: 4 },
      { itemId: 'blood_elixir', name: 'Elixir Darah Vampir', icon: '🧪', count: 2 },
    ],
    requiredGold: 90,
    description: 'Memberikan perlindungan luar biasa terhadap tebasan fisik dan racun.',
  },
  {
    id: 'craft_frost_rune_ring',
    resultItem: {
      id: 'frost_rune_ring',
      name: 'Cincin Rune Pembeku Jiwa',
      description: 'Aksesoris permata es yang mempercepat pemulihan energi dan meningkatkan kecepatan bertindak.',
      icon: '💍',
      category: 'equipment',
      equip_slot: 'accessory',
      attack_bonus: 10,
      defense_bonus: 6,
      speed_bonus: 25,
      heal_amount: 0,
      count: 1,
      is_stackable: false,
      value: 220,
      rarity: 'rare',
      color: '#38bdf8',
    },
    requiredMaterials: [
      { itemId: 'bone_fragment', name: 'Fragmen Tulang Kuno', icon: '🦴', count: 2 },
      { itemId: 'holy_water', name: 'Air Suci Suaka', icon: '💧', count: 1 },
    ],
    requiredGold: 75,
    description: 'Menjaga pikiran pemakainya tetap dingin di tengah kepanikan pertempuran.',
  },
];

export const DEFAULT_BESTIARY_ENTRIES: MonsterCodexEntry[] = [
  {
    id: 'skeleton',
    name: 'Tengkorak Terkutuk (Cursed Skeleton)',
    subtitle: 'Prajurit purba yang dibangkitkan dari kubur berkabut',
    type: 'skeleton',
    threatLevel: 'Rendah',
    lore: 'Sisa-sisa pengawal kerajaan kuno yang tulang-belulangnya digerakkan oleh sihir hitam necromancy. Mereka tidak mengenal rasa takut ataupun belas kasihan.',
    weaknesses: ['Holy', 'Fire'],
    resistances: ['Dark', 'Physical'],
    drops: [
      { name: 'Fragmen Tulang Kuno', icon: '🦴', rate: '85%' },
      { name: 'Koin Kuno', icon: '🪙', rate: '50%' },
    ],
    kills: 14,
    unlocked: true,
    sprite: 'skeleton',
  },
  {
    id: 'ghoul',
    name: 'Ghoul Pemakan Mayat (Blood Ghoul)',
    subtitle: 'Makhluk ganas haus darah segar',
    type: 'ghoul',
    threatLevel: 'Sedang',
    lore: 'Manusia yang tercemar oleh kutukan darah vampir dan membusuk hidup-hidup. Cakar mereka mengandung racun pemicu pendarahan tiada henti.',
    weaknesses: ['Fire', 'Holy'],
    resistances: ['Ice'],
    drops: [
      { name: 'Darah Terkutuk', icon: '💧', rate: '70%' },
      { name: 'Elixir Darah', icon: '🧪', rate: '35%' },
    ],
    kills: 9,
    unlocked: true,
    sprite: 'ghoul',
  },
  {
    id: 'vampire_bat',
    name: 'Kelelawar Malam Pemburu (Vampiric Bat)',
    subtitle: 'Mata dan telinga pengintai Lord Malakar',
    type: 'vampire_bat',
    threatLevel: 'Rendah',
    lore: 'Kawanan kelelawar pembawa penyakit yang mengintai di langit malam purnama darah. Kecepatan terbangnya tinggi namun rapuh terhadap serangan es dan api.',
    weaknesses: ['Fire', 'Ice'],
    resistances: ['Physical'],
    drops: [
      { name: 'Sayap Kelelawar Gelap', icon: '🦇', rate: '80%' },
      { name: 'Taring Kecil', icon: '⚡', rate: '40%' },
    ],
    kills: 18,
    unlocked: true,
    sprite: 'vampire_bat',
  },
  {
    id: 'boss_malakar',
    name: 'Lord Malakar sang Penguasa Darah',
    subtitle: 'Raja Vampir Katakomba Kuno Ravenfall',
    type: 'boss_malakar',
    threatLevel: 'Bos Ekstrem',
    lore: 'Bangsawan kuno berusia lima abad yang menguasai seni darah terlarang. Ia memegang Piala Darah Abadi (Crimson Chalice) yang menjadi sumber kutukan desa Ravenfall.',
    weaknesses: ['Holy', 'Fire'],
    resistances: ['Dark', 'Ice', 'Physical'],
    drops: [
      { name: 'Piala Darah Abadi', icon: '🏆', rate: '100%' },
      { name: 'Scythe Bulan Darah', icon: '🌙', rate: '100%' },
    ],
    kills: 1,
    unlocked: true,
    sprite: 'boss_malakar',
  },
];

export const DEFAULT_QUEST_LOG: QuestLogEntry[] = [
  {
    id: 'main_blood_curse',
    title: 'Musnahkan Kutukan Darah Ravenfall',
    category: 'Main',
    giver: 'Inkuisitor Balthazar',
    description: 'Selidiki Katakomba Tenggara, kalahkan Lord Malakar, dan rebut kembali Piala Darah Abadi untuk menyucikan desa.',
    currentCount: 0,
    targetCount: 1,
    targetLabel: 'Kalahkan Lord Malakar & Ambil Piala Darah',
    rewardGold: 150,
    rewardExp: 500,
    rewardItemName: 'Scythe Bulan Darah (Crimson Scythe)',
    status: 'in_progress',
  },
  {
    id: 'side_skeleton_cull',
    title: 'Pembersihan Tulang Belulang Kuburan',
    category: 'Side',
    giver: 'Tetua Eldrin',
    description: 'Basmi kerangka mayat hidup yang mengusik ketenteraman makam leluhur di Pemakaman Berkabut.',
    currentCount: 3,
    targetCount: 5,
    targetLabel: 'Tengkorak Terkutuk Ditumbangkan',
    rewardGold: 60,
    rewardExp: 150,
    rewardItemName: 'Air Suci Suaka (Holy Water)',
    status: 'in_progress',
  },
  {
    id: 'side_forge_supplies',
    title: 'Bahan Baku Tempaan Besi Hitam',
    category: 'Side',
    giver: 'Viktor sang Pandai Besi',
    description: 'Bawakan fragmen tulang dan bijih besi untuk menempa senjata perak berstandar katedral.',
    currentCount: 2,
    targetCount: 3,
    targetLabel: 'Material Logam Terkumpul',
    rewardGold: 80,
    rewardExp: 180,
    rewardItemName: 'Gothic Bone Blade',
    status: 'in_progress',
  },
  {
    id: 'side_lilith_elixir',
    title: 'Eksperimen Ramuan Rahasia Alkemis',
    category: 'Side',
    giver: 'Lilith sang Alkemis',
    description: 'Dapatkan sampel intisari darah segar dari Ghoul untuk meneliti penawar kutukan vampirisme.',
    currentCount: 1,
    targetCount: 2,
    targetLabel: 'Sampel Darah Terkumpul',
    rewardGold: 70,
    rewardExp: 200,
    rewardItemName: 'Elixir Darah Vampir x2',
    status: 'in_progress',
  },
];

export function createEncounterEnemy(type: 'skeleton' | 'ghoul' | 'bat' | 'malakar'): TurnBasedEnemy {
  switch (type) {
    case 'skeleton':
      return {
        id: `enc_skel_${Date.now()}`,
        name: 'Tengkorak Terkutuk Kuno',
        type: 'skeleton',
        hp: 75,
        maxHp: 75,
        attack: 18,
        defense: 8,
        speed: 12,
        weaknesses: ['Holy', 'Fire'],
        resistances: ['Dark', 'Physical'],
        staggerPoints: 2,
        maxStagger: 2,
        isStaggered: false,
        statusEffects: [],
        sprite: 'skeleton',
        expReward: 45,
        goldReward: 18,
        dropItemId: 'bone_fragment',
      };
    case 'ghoul':
      return {
        id: `enc_ghoul_${Date.now()}`,
        name: 'Blood Ghoul Lapar',
        type: 'ghoul',
        hp: 110,
        maxHp: 110,
        attack: 24,
        defense: 10,
        speed: 15,
        weaknesses: ['Fire', 'Holy'],
        resistances: ['Ice'],
        staggerPoints: 3,
        maxStagger: 3,
        isStaggered: false,
        statusEffects: [],
        sprite: 'ghoul',
        expReward: 65,
        goldReward: 25,
        dropItemId: 'blood_elixir',
      };
    case 'bat':
      return {
        id: `enc_bat_${Date.now()}`,
        name: 'Kawanan Kelelawar Bayangan',
        type: 'vampire_bat',
        hp: 55,
        maxHp: 55,
        attack: 16,
        defense: 4,
        speed: 22,
        weaknesses: ['Fire', 'Ice'],
        resistances: ['Physical'],
        staggerPoints: 2,
        maxStagger: 2,
        isStaggered: false,
        statusEffects: [],
        sprite: 'vampire_bat',
        expReward: 35,
        goldReward: 14,
        dropItemId: 'bone_fragment',
      };
    case 'malakar':
    default:
      return {
        id: `enc_boss_${Date.now()}`,
        name: 'Lord Malakar (Penguasa Darah)',
        type: 'boss_malakar',
        hp: 280,
        maxHp: 280,
        attack: 38,
        defense: 16,
        speed: 19,
        weaknesses: ['Holy', 'Fire'],
        resistances: ['Dark', 'Ice', 'Physical'],
        staggerPoints: 5,
        maxStagger: 5,
        isStaggered: false,
        statusEffects: [],
        sprite: 'boss_malakar',
        expReward: 300,
        goldReward: 150,
        dropItemId: 'crimson_chalice',
      };
  }
}

export const DEFAULT_SETTINGS: AudioVisualSettings = {
  bgmVolume: 0.7,
  sfxVolume: 0.85,
  hdMode: true,
  bloodMoon: true,
  mistEnabled: true,
  crtFilter: false,
};

export const DEFAULT_PARTY = DEFAULT_PARTY_MEMBERS;
export const DEFAULT_SKILL_NODES = DEFAULT_SKILL_TREE_NODES;
export const DEFAULT_MONSTER_CODEX = DEFAULT_BESTIARY_ENTRIES;
export const DEFAULT_QUESTS = DEFAULT_QUEST_LOG;
export const DEFAULT_ENEMIES_TACTICAL = {
  skeleton_warrior: createEncounterEnemy('skeleton'),
  crypt_ghoul: createEncounterEnemy('ghoul'),
  vampire_bat: createEncounterEnemy('bat'),
  lord_malakar: createEncounterEnemy('malakar'),
};
