import { WorldChunk, WorldObject, NPC, Enemy, ItemData, DialogueNode } from '../types/game';

export const CHUNK_WIDTH = 640;
export const CHUNK_HEIGHT = 360;

export const INITIAL_CHUNKS: WorldChunk[] = [
  // Baris 0 (Y: 0 - 360)
  {
    id: 'domain_village',
    name: 'Desa Ravenfall (Cursed Village)',
    subtitle: 'Tempat Bernaung Terakhir Manusia • Titik Awal Pemburu',
    dangerLevel: 'Lobby Suaka',
    dangerColor: '#38bdf8',
    x: 0,
    y: 0,
    pixelX: 0,
    pixelY: 0,
    width: CHUNK_WIDTH,
    height: CHUNK_HEIGHT,
    biome: 'village',
    active: true,
  },
  {
    id: 'domain_cemetery',
    name: 'Pemakaman Bulan Darah (Cemetery)',
    subtitle: 'Makam Para Martir yang Dibangkitkan Kutukan Darah',
    dangerLevel: 'Lobby Suaka',
    dangerColor: '#38bdf8',
    x: 1,
    y: 0,
    pixelX: CHUNK_WIDTH,
    pixelY: 0,
    width: CHUNK_WIDTH,
    height: CHUNK_HEIGHT,
    biome: 'cemetery',
    active: false,
  },
  {
    id: 'domain_swamp',
    name: 'Rawa Kabut Beracun (Poison Swamp)',
    subtitle: 'Rawa Beracun Sarang Kelelawar Penghisap Jiwa',
    dangerLevel: 'Lobby Suaka',
    dangerColor: '#38bdf8',
    x: 2,
    y: 0,
    pixelX: CHUNK_WIDTH * 2,
    pixelY: 0,
    width: CHUNK_WIDTH,
    height: CHUNK_HEIGHT,
    biome: 'swamp',
    active: false,
  },
  // Baris 1 (Y: 360 - 720)
  {
    id: 'domain_cathedral',
    name: 'Katedral Suci (Holy Cathedral)',
    subtitle: 'Katedral Kuno Bertabur Kaca Mawar dan Ratapan Roh Kudus',
    dangerLevel: 'Lobby Suaka',
    dangerColor: '#38bdf8',
    x: 0,
    y: 1,
    pixelX: 0,
    pixelY: CHUNK_HEIGHT,
    width: CHUNK_WIDTH,
    height: CHUNK_HEIGHT,
    biome: 'cathedral',
    active: false,
  },
  {
    id: 'domain_ruins',
    name: 'Menara Reruntuhan Bintang (Ruined Astral Tower)',
    subtitle: 'Gerbang Suci yang Hancur Akibat Peperangan Iblis Purba',
    dangerLevel: 'Lobby Suaka',
    dangerColor: '#38bdf8',
    x: 1,
    y: 1,
    pixelX: CHUNK_WIDTH,
    pixelY: CHUNK_HEIGHT,
    width: CHUNK_WIDTH,
    height: CHUNK_HEIGHT,
    biome: 'ruins',
    active: false,
  },
  {
    id: 'domain_bone_valley',
    name: 'Lembah Tulang Purba (Valley of Ancient Bones)',
    subtitle: 'Kuburan Kerangka Raksasa dan Prajurit Perang Purba',
    dangerLevel: 'Lobby Suaka',
    dangerColor: '#38bdf8',
    x: 2,
    y: 1,
    pixelX: CHUNK_WIDTH * 2,
    pixelY: CHUNK_HEIGHT,
    width: CHUNK_WIDTH,
    height: CHUNK_HEIGHT,
    biome: 'bone_valley',
    active: false,
  },
  // Baris 2 (Y: 720 - 1080)
  {
    id: 'domain_castle',
    name: 'Aula Takhta Kastil (Castle Throne Hall)',
    subtitle: 'Singgasana Takhta Drakula yang Ditinggalkan Berabad-abad',
    dangerLevel: 'Lobby Suaka',
    dangerColor: '#38bdf8',
    x: 0,
    y: 2,
    pixelX: 0,
    pixelY: CHUNK_HEIGHT * 2,
    width: CHUNK_WIDTH,
    height: CHUNK_HEIGHT,
    biome: 'vampire_sanctum',
    active: false,
  },
  {
    id: 'domain_crypt',
    name: 'Labirin Kripta Kuno (Ancient Crypt Labyrinth)',
    subtitle: 'Sarang Kediaman Lord Malakar sang Raja Mayat Hidup',
    dangerLevel: 'Lobby Suaka',
    dangerColor: '#38bdf8',
    x: 1,
    y: 2,
    pixelX: CHUNK_WIDTH,
    pixelY: CHUNK_HEIGHT * 2,
    width: CHUNK_WIDTH,
    height: CHUNK_HEIGHT,
    biome: 'crypt',
    active: false,
  },
  {
    id: 'domain_white_cross',
    name: 'Benteng Salib Putih (White Cross Fortress)',
    subtitle: 'Benteng Pertahanan Ordo Salib Perak di Perbatasan Kegelapan',
    dangerLevel: 'Lobby Suaka',
    dangerColor: '#38bdf8',
    x: 2,
    y: 2,
    pixelX: CHUNK_WIDTH * 2,
    pixelY: CHUNK_HEIGHT * 2,
    width: CHUNK_WIDTH,
    height: CHUNK_HEIGHT,
    biome: 'cathedral',
    active: false,
  },
  // Baris 3 (Y: 1080 - 1440) - Ekspansi Dunia Terbuka Gotik
  {
    id: 'domain_rose_garden',
    name: 'Taman Mawar Hitam (Black Rose Garden)',
    subtitle: 'Taman Bunga Berduri Darah Peristirahatan Bangsawan Drakula',
    dangerLevel: 'Lobby Suaka',
    dangerColor: '#38bdf8',
    x: 0,
    y: 3,
    pixelX: 0,
    pixelY: CHUNK_HEIGHT * 3,
    width: CHUNK_WIDTH,
    height: CHUNK_HEIGHT,
    biome: 'rose_garden',
    active: false,
  },
  {
    id: 'domain_hellfire',
    name: 'Gerbang Api Neraka (Hellfire Gate)',
    subtitle: 'Ngarai Terbelah Sumber Energi Void Kegelapan Lord Malakar',
    dangerLevel: 'Lobby Suaka',
    dangerColor: '#38bdf8',
    x: 1,
    y: 3,
    pixelX: CHUNK_WIDTH,
    pixelY: CHUNK_HEIGHT * 3,
    width: CHUNK_WIDTH,
    height: CHUNK_HEIGHT,
    biome: 'abyss',
    active: false,
  },
  {
    id: 'domain_light_sanctuary',
    name: 'Suaka Cahaya Abadi (Eternal Light Sanctuary)',
    subtitle: 'Puncak Tertinggi di Mana Cahaya Suci Tak Pernah Padam',
    dangerLevel: 'Lobby Suaka',
    dangerColor: '#38bdf8',
    x: 2,
    y: 3,
    pixelX: CHUNK_WIDTH * 2,
    pixelY: CHUNK_HEIGHT * 3,
    width: CHUNK_WIDTH,
    height: CHUNK_HEIGHT,
    biome: 'village',
    active: false,
  },
];

export const INITIAL_ITEMS: Record<string, ItemData> = {
  blood_elixir: {
    id: 'blood_elixir',
    name: 'Elixir Darah Vampir',
    description: 'Ramuan kental merah menyala yang memulihkan 45 HP seketika.',
    category: 'consumable',
    icon: '🧪',
    is_stackable: true,
    count: 3,
    heal_amount: 45,
    value: 30,
  },
  holy_water: {
    id: 'holy_water',
    name: 'Air Suci Pengusir Iblis',
    description: 'Air suci yang diberkati oleh Suster Genevieve. Memulihkan 30 HP.',
    category: 'consumable',
    icon: '💧',
    is_stackable: true,
    count: 2,
    heal_amount: 30,
    value: 15,
  },
  silver_rapier: {
    id: 'silver_rapier',
    name: 'Rapier Perak Pembasmi Mayat (+12 ATK, +8 SPD)',
    description: 'Bilah perak anggun yang ditempa untuk menebas makhluk kegelapan secara presisi.',
    category: 'equipment',
    equip_slot: 'weapon',
    icon: '🗡️',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 12,
    speed_bonus: 8,
    value: 120,
  },
  purified_blade: {
    id: 'purified_blade',
    name: 'Pedang Perak Suci Tertempa (+25 ATK, +2 DEF)',
    description: 'Karya agung Viktor Pandai Besi yang disepuh bara perak suci anti-vampir.',
    category: 'equipment',
    equip_slot: 'weapon',
    icon: '⚔️',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 25,
    defense_bonus: 2,
    value: 260,
  },
  crimson_scythe: {
    id: 'crimson_scythe',
    name: 'Sabit Bulan Darah (+35 ATK, +15 SPD)',
    description: 'Senjata sabit lengkung pusaka bangsawan darah yang membelah angin dengan kecepatan kilat.',
    category: 'equipment',
    equip_slot: 'weapon',
    icon: '🌙',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 35,
    speed_bonus: 15,
    value: 350,
  },
  venom_stiletto: {
    id: 'venom_stiletto',
    name: 'Belati Racun Rawa (+18 ATK, +20 SPD)',
    description: 'Belati tipis berlumur racun getah rawa Eldrin, menyerang dengan kelincahan tinggi.',
    category: 'equipment',
    equip_slot: 'weapon',
    icon: '🗡️',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 18,
    speed_bonus: 20,
    value: 180,
  },
  hunter_coat: {
    id: 'hunter_coat',
    name: 'Mantel Kulit Pemburu Gagak (+4 DEF, +30 HP)',
    description: 'Mantel kulit hitam tahan cakar binatang malam berhiaskan bulu gagak mistis.',
    category: 'equipment',
    equip_slot: 'armor',
    icon: '🥋',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    defense_bonus: 4,
    max_hp_bonus: 30,
    speed_bonus: 6,
    value: 160,
  },
  templar_cuirass: {
    id: 'templar_cuirass',
    name: 'Zirah Besi Ksatria Templar (+8 DEF, +50 HP)',
    description: 'Plat baja kokoh berpahat salib suci yang mampu meredam hantaman keras para raksasa.',
    category: 'equipment',
    equip_slot: 'armor',
    icon: '🛡️',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    defense_bonus: 8,
    max_hp_bonus: 50,
    value: 280,
  },
  gothic_dress: {
    id: 'gothic_dress',
    name: 'Gaun Sutra Hitam Berenda (+3 DEF, +35 HP, +8 ATK)',
    description: 'Gaun anggun berenda gotik yang ditenun dengan benang sihir pelindung.',
    category: 'equipment',
    equip_slot: 'armor',
    icon: '👗',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    defense_bonus: 3,
    max_hp_bonus: 35,
    attack_bonus: 8,
    value: 220,
  },
  crimson_chalice: {
    id: 'crimson_chalice',
    name: 'Piala Darah Abadi',
    description: 'Relik pusaka kegelapan Lord Malakar yang menjadi sumber kutukan di Ravenfall.',
    category: 'quest',
    icon: '🏆',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    value: 300,
  },
  bone_fragment: {
    id: 'bone_fragment',
    name: 'Pecahan Tulang Gelap',
    description: 'Sisa kerangka mayat hidup berhawa dingin untuk bahan tempa dan alkimia.',
    category: 'material',
    icon: '🦴',
    is_stackable: true,
    count: 2,
    heal_amount: 0,
    value: 12,
  },
  holy_rosary: {
    id: 'holy_rosary',
    name: 'Tasbih Suci Genevieve (+30 HP, +3 DEF)',
    description: 'Diberkati dengan air mata sang biarawati buta, meningkatkan ketahanan jiwa dan raga.',
    category: 'equipment',
    equip_slot: 'accessory',
    icon: '📿',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    max_hp_bonus: 30,
    defense_bonus: 3,
    value: 180,
  },
  crusader_ring: {
    id: 'crusader_ring',
    name: 'Cincin Ksatria Godfrey (+8 ATK, +2 DEF)',
    description: 'Cincin perak berukir lambang perang salib kuno, memancarkan aura keberanian membara.',
    category: 'equipment',
    equip_slot: 'accessory',
    icon: '💍',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 8,
    defense_bonus: 2,
    value: 150,
  },
  blood_amulet: {
    id: 'blood_amulet',
    name: 'Amulet Tetes Darah Abadi (+12 ATK, +20 HP)',
    description: 'Batu delima berkilau tetesan darah murni vampire royal yang meningkatkan daya tempur.',
    category: 'equipment',
    equip_slot: 'accessory',
    icon: '📿',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 12,
    max_hp_bonus: 20,
    value: 240,
  },
  alchemist_pouch: {
    id: 'alchemist_pouch',
    name: 'Kantong Ramuan Alkemis (+25 SPD, +2 DEF)',
    description: 'Kantong kulit berisi esens herbal Eldrin yang meringankan langkah kaki pemburu.',
    category: 'equipment',
    equip_slot: 'accessory',
    icon: '🎒',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    speed_bonus: 25,
    defense_bonus: 2,
    value: 160,
  },
  astral_wand: {
    id: 'astral_wand',
    name: 'Tongkat Bintang Celestine (+24 ATK, +15 SPD)',
    description: 'Tongkat sihir kristal astral yang memancarkan pendar konstelasi ungu bintang malam.',
    category: 'equipment',
    equip_slot: 'weapon',
    icon: '🔮',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 24,
    speed_bonus: 15,
    value: 280,
  },
  abyss_reaper: {
    id: 'abyss_reaper',
    name: 'Bilah Nether Abyss (+32 ATK, +30 HP)',
    description: 'Pedang besar yang ditempa dari kristal jurang purba dengan ketajaman pemotong jiwa.',
    category: 'equipment',
    equip_slot: 'weapon',
    icon: '⚔️',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 32,
    max_hp_bonus: 30,
    value: 350,
  },
  rose_rapier: {
    id: 'rose_rapier',
    name: 'Rapier Mawar Hitam (+22 ATK, +10 SPD, +4 DEF)',
    description: 'Bilah rapier bangsawan berhulu kembang mawar hitam berpelindung duri baja.',
    category: 'equipment',
    equip_slot: 'weapon',
    icon: '🗡️',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 22,
    speed_bonus: 10,
    defense_bonus: 4,
    value: 260,
  },
  astral_robe: {
    id: 'astral_robe',
    name: 'Jubah Sutra Bintang (+12 DEF, +40 HP, +15 SPD)',
    description: 'Jubah tenunan benang kosmik yang menyerap hempasan sihir dan meringankan gerakan.',
    category: 'equipment',
    equip_slot: 'armor',
    icon: '👘',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    defense_bonus: 12,
    max_hp_bonus: 40,
    speed_bonus: 15,
    value: 290,
  },
  abyssal_cuirass: {
    id: 'abyssal_cuirass',
    name: 'Zirah Plat Nether Abyss (+18 DEF, +60 HP)',
    description: 'Zirah baja hitam pekat yang ditempa di dalam jurang kegelapan purba.',
    category: 'equipment',
    equip_slot: 'armor',
    icon: '🛡️',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    defense_bonus: 18,
    max_hp_bonus: 60,
    value: 380,
  },
  rose_corsage: {
    id: 'rose_corsage',
    name: 'Bros Mawar Hitam Terlarang (+14 ATK, +6 DEF, +25 HP)',
    description: 'Pusaka mawar yang diawetkan oleh esens darah bangsawan klan vampir.',
    category: 'equipment',
    equip_slot: 'accessory',
    icon: '🥀',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 14,
    defense_bonus: 6,
    max_hp_bonus: 25,
    value: 220,
  },
  crow_feather_charm: {
    id: 'crow_feather_charm',
    name: 'Jimat Bulu Gagak Morrigan (+35 SPD, +8 ATK)',
    description: 'Bulu gagak hitam gaib yang memanipulasi angin bayangan untuk mempercepat tebasan.',
    category: 'equipment',
    equip_slot: 'accessory',
    icon: '🪶',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    speed_bonus: 35,
    attack_bonus: 8,
    value: 190,
  },
  astral_elixir: {
    id: 'astral_elixir',
    name: 'Elixir Cahaya Bintang (Heal 75 HP)',
    description: 'Cairan ungu berkilau bintang yang memulihkan 75 HP dan menyucikan kutukan jiwa.',
    category: 'consumable',
    icon: '✨',
    is_stackable: true,
    count: 2,
    heal_amount: 75,
    value: 60,
  },
  rose_dew: {
    id: 'rose_dew',
    name: 'Embun Mawar Hitam (Heal 55 HP)',
    description: 'Tetesan embun mawar malam beraroma wangi manis yang memulihkan 55 HP.',
    category: 'consumable',
    icon: '🌹',
    is_stackable: true,
    count: 3,
    heal_amount: 55,
    value: 40,
  },
  holy_broadsword: {
    id: 'holy_broadsword',
    name: 'Holy Broadsword',
    description: 'Pedang suci yang memancarkan cahaya emas pemberangus kegelapan.',
    category: 'equipment',
    equip_slot: 'weapon',
    rarity: 'rare',
    icon: '⚔️',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 45,
    defense_bonus: 10,
    value: 450,
  },
  blood_scythe: {
    id: 'blood_scythe',
    name: 'Blood Scythe',
    description: 'Sabit bulan darah dengan pusaran kabut merah yang haus jiwa.',
    category: 'equipment',
    equip_slot: 'weapon',
    rarity: 'epic',
    icon: '🌙',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 65,
    speed_bonus: -5,
    value: 800,
  },
  viper_fang: {
    id: 'viper_fang',
    name: 'Viper Fang',
    description: 'Tebasan kembar beracun hijau neon dengan tetesan racun asam.',
    category: 'equipment',
    equip_slot: 'weapon',
    rarity: 'uncommon',
    icon: '🐍',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 35,
    speed_bonus: 10,
    value: 300,
  },
  astral_scepter: {
    id: 'astral_scepter',
    name: 'Astral Scepter',
    description: 'Konstelasi starlight kosmik dengan bintang berkilau.',
    category: 'equipment',
    equip_slot: 'weapon',
    rarity: 'epic',
    icon: '🪄',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 55,
    max_hp_bonus: 20,
    value: 750,
  },
  void_reaver: {
    id: 'void_reaver',
    name: 'Void Reaver',
    description: 'Sobekan dimensi hampa ungu tua void yang melahap cahaya.',
    category: 'equipment',
    equip_slot: 'weapon',
    rarity: 'legendary',
    icon: '🌑',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 85,
    value: 1500,
  },
  crimson_rose_thorn: {
    id: 'crimson_rose_thorn',
    name: 'Crimson Rose Thorn',
    description: 'Badai tebasan kelopak bunga mawar merah tua yang mematikan.',
    category: 'equipment',
    equip_slot: 'weapon',
    rarity: 'epic',
    icon: '🥀',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 50,
    speed_bonus: 5,
    value: 650,
  },
  hellfire_blade: {
    id: 'hellfire_blade',
    name: 'Hellfire & Executioner',
    description: 'Gelombang kejut api neraka dan bara panas membara.',
    category: 'equipment',
    equip_slot: 'weapon',
    rarity: 'legendary',
    icon: '🔥',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 90,
    defense_bonus: -10,
    value: 2000,
  },
  frost_mourne: {
    id: 'frost_mourne',
    name: 'Frost Mourne',
    description: 'Uap es biru dingin abadi yang membekukan darah musuh.',
    category: 'equipment',
    equip_slot: 'weapon',
    rarity: 'epic',
    icon: '❄️',
    is_stackable: false,
    count: 1,
    heal_amount: 0,
    attack_bonus: 60,
    defense_bonus: 15,
    value: 900,
  },
};

export const INITIAL_NPCS: NPC[] = [
  {
    id: 'npc_trader',
    name: 'Ghazal sang Pedagang Misterius',
    title: 'Penjual Barang Langka',
    affiliation: 'Pengembara Void',
    role: 'merchant',
    mood: 'Misterius & Ramah',
    x: 1650,
    y: 250,
    direction: 'left',
    sprite: 'vladimir',
    dialogueId: 'trader_intro',
    voicePitch: 120,
    lore: 'Pedangang yang melintasi berbagai dimensi untuk menjual barang ajaib.',
    portraitTheme: {
      primaryColor: '#8b5cf6',
      accentColor: '#6d28d9',
      bgStyle: 'cemetery',
      headwear: 'Jubah Hitam & Kacamata Emas',
      eyeGlowColor: '#c084fc',
      quote: '"Aku memiliki apa yang kau butuhkan... asalkan kau punya emasnya."',
    },
  },
  {
    id: 'npc_dialogue_cathedral',
    name: 'Pengembara Tersesat',
    title: 'Jiwa Tanpa Arah',
    affiliation: 'Korban Ravenfall',
    role: 'lore',
    mood: 'Sedih',
    x: 200,
    y: 580,
    direction: 'down',
    sprite: 'ghost_knight',
    dialogueId: 'dialogue_only_cathedral',
    voicePitch: 100 + 0,
    lore: 'Jiwa yang terjebak dalam putaran waktu di Ravenfall.',
    portraitTheme: {
      primaryColor: '#94a3b8',
      accentColor: '#64748b',
      bgStyle: 'cemetery',
      headwear: 'Helm Hancur',
      eyeGlowColor: '#cbd5e1',
      quote: '"Aku hanya ingin pulang..."',
    },
  },
  {
    id: 'npc_dialogue_ruins',
    name: 'Pengembara Tersesat',
    title: 'Jiwa Tanpa Arah',
    affiliation: 'Korban Ravenfall',
    role: 'lore',
    mood: 'Sedih',
    x: 800,
    y: 500,
    direction: 'down',
    sprite: 'ghost_knight',
    dialogueId: 'dialogue_only_ruins',
    voicePitch: 100 + 10,
    lore: 'Jiwa yang terjebak dalam putaran waktu di Ravenfall.',
    portraitTheme: {
      primaryColor: '#94a3b8',
      accentColor: '#64748b',
      bgStyle: 'cemetery',
      headwear: 'Helm Hancur',
      eyeGlowColor: '#cbd5e1',
      quote: '"Aku hanya ingin pulang..."',
    },
  },
  {
    id: 'npc_dialogue_bone_valley',
    name: 'Pengembara Tersesat',
    title: 'Jiwa Tanpa Arah',
    affiliation: 'Korban Ravenfall',
    role: 'lore',
    mood: 'Sedih',
    x: 1500,
    y: 550,
    direction: 'down',
    sprite: 'ghost_knight',
    dialogueId: 'dialogue_only_bone_valley',
    voicePitch: 100 + 20,
    lore: 'Jiwa yang terjebak dalam putaran waktu di Ravenfall.',
    portraitTheme: {
      primaryColor: '#94a3b8',
      accentColor: '#64748b',
      bgStyle: 'cemetery',
      headwear: 'Helm Hancur',
      eyeGlowColor: '#cbd5e1',
      quote: '"Aku hanya ingin pulang..."',
    },
  },
  {
    id: 'npc_dialogue_castle',
    name: 'Pengembara Tersesat',
    title: 'Jiwa Tanpa Arah',
    affiliation: 'Korban Ravenfall',
    role: 'lore',
    mood: 'Sedih',
    x: 200,
    y: 900,
    direction: 'down',
    sprite: 'ghost_knight',
    dialogueId: 'dialogue_only_castle',
    voicePitch: 100 + 30,
    lore: 'Jiwa yang terjebak dalam putaran waktu di Ravenfall.',
    portraitTheme: {
      primaryColor: '#94a3b8',
      accentColor: '#64748b',
      bgStyle: 'cemetery',
      headwear: 'Helm Hancur',
      eyeGlowColor: '#cbd5e1',
      quote: '"Aku hanya ingin pulang..."',
    },
  },
  {
    id: 'npc_dialogue_crypt',
    name: 'Pengembara Tersesat',
    title: 'Jiwa Tanpa Arah',
    affiliation: 'Korban Ravenfall',
    role: 'lore',
    mood: 'Sedih',
    x: 800,
    y: 900,
    direction: 'down',
    sprite: 'ghost_knight',
    dialogueId: 'dialogue_only_crypt',
    voicePitch: 100 + 40,
    lore: 'Jiwa yang terjebak dalam putaran waktu di Ravenfall.',
    portraitTheme: {
      primaryColor: '#94a3b8',
      accentColor: '#64748b',
      bgStyle: 'cemetery',
      headwear: 'Helm Hancur',
      eyeGlowColor: '#cbd5e1',
      quote: '"Aku hanya ingin pulang..."',
    },
  },
  {
    id: 'npc_dialogue_white_cross',
    name: 'Pengembara Tersesat',
    title: 'Jiwa Tanpa Arah',
    affiliation: 'Korban Ravenfall',
    role: 'lore',
    mood: 'Sedih',
    x: 1450,
    y: 950,
    direction: 'down',
    sprite: 'ghost_knight',
    dialogueId: 'dialogue_only_white_cross',
    voicePitch: 100 + 50,
    lore: 'Jiwa yang terjebak dalam putaran waktu di Ravenfall.',
    portraitTheme: {
      primaryColor: '#94a3b8',
      accentColor: '#64748b',
      bgStyle: 'cemetery',
      headwear: 'Helm Hancur',
      eyeGlowColor: '#cbd5e1',
      quote: '"Aku hanya ingin pulang..."',
    },
  },
  {
    id: 'npc_dialogue_rose_garden',
    name: 'Pengembara Tersesat',
    title: 'Jiwa Tanpa Arah',
    affiliation: 'Korban Ravenfall',
    role: 'lore',
    mood: 'Sedih',
    x: 150,
    y: 1250,
    direction: 'down',
    sprite: 'ghost_knight',
    dialogueId: 'dialogue_only_rose_garden',
    voicePitch: 100 + 60,
    lore: 'Jiwa yang terjebak dalam putaran waktu di Ravenfall.',
    portraitTheme: {
      primaryColor: '#94a3b8',
      accentColor: '#64748b',
      bgStyle: 'cemetery',
      headwear: 'Helm Hancur',
      eyeGlowColor: '#cbd5e1',
      quote: '"Aku hanya ingin pulang..."',
    },
  },
  {
    id: 'npc_dialogue_hellfire',
    name: 'Pengembara Tersesat',
    title: 'Jiwa Tanpa Arah',
    affiliation: 'Korban Ravenfall',
    role: 'lore',
    mood: 'Sedih',
    x: 850,
    y: 1250,
    direction: 'down',
    sprite: 'ghost_knight',
    dialogueId: 'dialogue_only_hellfire',
    voicePitch: 100 + 70,
    lore: 'Jiwa yang terjebak dalam putaran waktu di Ravenfall.',
    portraitTheme: {
      primaryColor: '#94a3b8',
      accentColor: '#64748b',
      bgStyle: 'cemetery',
      headwear: 'Helm Hancur',
      eyeGlowColor: '#cbd5e1',
      quote: '"Aku hanya ingin pulang..."',
    },
  },
  {
    id: 'npc_dialogue_light_sanctuary',
    name: 'Pengembara Tersesat',
    title: 'Jiwa Tanpa Arah',
    affiliation: 'Korban Ravenfall',
    role: 'lore',
    mood: 'Sedih',
    x: 1500,
    y: 1200,
    direction: 'down',
    sprite: 'ghost_knight',
    dialogueId: 'dialogue_only_light_sanctuary',
    voicePitch: 100 + 80,
    lore: 'Jiwa yang terjebak dalam putaran waktu di Ravenfall.',
    portraitTheme: {
      primaryColor: '#94a3b8',
      accentColor: '#64748b',
      bgStyle: 'cemetery',
      headwear: 'Helm Hancur',
      eyeGlowColor: '#cbd5e1',
      quote: '"Aku hanya ingin pulang..."',
    },
  },

  {
    id: 'npc_dungeon_master',
    name: 'Dungeon Master',
    title: 'Penjaga Gerbang Menara 100 Lantai',
    affiliation: 'Ksatria Kuno Gerbang Dimensi',
    role: 'guide',
    mood: 'Misterius & Berwibawa',
    x: 320,
    y: 110,
    direction: 'down',
    sprite: 'dungeon_master',
    dialogueId: 'dungeon_master_intro',
    hasQuest: false,
    questCompleted: false,
    voicePitch: 150,
    lore: 'Ksatria agung berzirah putih penjaga portal dimensi menuju Menara 100 Lantai. Seluruh monster dunia kini tersegel di dalam menaranya.',
    portraitTheme: {
      primaryColor: '#eab308',
      accentColor: '#ca8a04',
      bgStyle: 'cathedral',
      headwear: 'Helm Mahkota Baja Putih Emas & Sayap Malaikat',
      eyeGlowColor: '#fde047',
      quote: '"Di balik gerbang ini terbentang 100 lantai neraka dan takhta para dewa. Apakah pedangmu siap, Ksatria Putih?"',
    },
  },
  {
    id: 'npc_inquisitor',
    name: 'Inkuisitor Balthazar',
    title: 'Kepala Ordo Salib Perak',
    affiliation: 'Ordo Suci Ravenfall',
    role: 'quest_giver',
    mood: 'Tegas & Berwibawa',
    x: 230,
    y: 150,
    direction: 'down',
    sprite: 'inquisitor',
    dialogueId: 'inquisitor_intro',
    hasQuest: true,
    questCompleted: false,
    voicePitch: 220,
    lore: 'Pemburu iblis berpengalaman yang telah mengabdikan hidupnya demi menumpas sekte vampir.',
    portraitTheme: {
      primaryColor: '#ef4444',
      accentColor: '#f59e0b',
      bgStyle: 'village',
      headwear: 'Topi Pemburu Bertepi Lebar & Mantel Merah',
      eyeGlowColor: '#fbbf24',
      quote: '"Darah iblis takkan pernah menyucikan tanah para leluhur kita."',
    },
  },
  {
    id: 'npc_carmilla',
    name: 'Lady Carmilla',
    title: 'Bangsawan Darah Terkutuk',
    affiliation: 'Klan Bayangan Malam',
    role: 'merchant',
    mood: 'Misterius & Memikat',
    x: 430,
    y: 180,
    direction: 'left',
    sprite: 'carmilla',
    dialogueId: 'carmilla_intro',
    voicePitch: 380,
    lore: 'Bangsawan yang terselubung cadar sutra gelap. Di balik keanggunannya, ia menyimpan rahasia kutukan darah abadi.',
    portraitTheme: {
      primaryColor: '#e11d48',
      accentColor: '#881337',
      bgStyle: 'crypt',
      headwear: 'Cadar Sutra Hitam Berhias Mutiara Darah',
      eyeGlowColor: '#f43f5e',
      quote: '"Malam ini begitu dingin, pemburu... Apakah nadimu masih berdegup hangat?"',
    },
  },
  {
    id: 'npc_blacksmith',
    name: 'Viktor sang Pandai Besi',
    title: 'Penempa Senjata Perak Terkutuk',
    affiliation: 'Bengkel Api Abadi Ravenfall',
    role: 'blacksmith',
    mood: 'Kasar namun Setia',
    x: 130,
    y: 220,
    direction: 'right',
    sprite: 'blacksmith',
    dialogueId: 'blacksmith_intro',
    voicePitch: 180,
    lore: 'Satu-satunya pandai besi yang mengetahui rahasia melebur bijih perak suci untuk membelah daging mayat hidup.',
    portraitTheme: {
      primaryColor: '#f97316',
      accentColor: '#7c2d12',
      bgStyle: 'forge',
      headwear: 'Apron Kulit Tebal & Kacamata Pelindung Bara',
      eyeGlowColor: '#fdba74',
      quote: '"Bawakan aku logam perak dan pecahan tulang, niscaya kuciptakan pedang pemenggal kepala iblis!"',
    },
  },
  {
    id: 'npc_gravekeeper',
    name: 'Morgath si Penjaga Kubur',
    title: 'Penggali Makam Kuno',
    affiliation: 'Pemakaman Berkabut Ravenfall',
    role: 'guide',
    mood: 'Murung & Waspada',
    x: 860,
    y: 160,
    direction: 'down',
    sprite: 'gravekeeper',
    dialogueId: 'gravekeeper_intro',
    voicePitch: 160,
    lore: 'Pria tua bungkuk pembawa sekop berkarat yang hafal setiap nama di atas batu nisan pemakaman.',
    portraitTheme: {
      primaryColor: '#78716c',
      accentColor: '#44403c',
      bgStyle: 'cemetery',
      headwear: 'Tudung Karung Usang & Lentera Minyak Temaram',
      eyeGlowColor: '#a8a29e',
      quote: '"Jangan injak tanah basah itu... mereka yang tertidur di bawahnya sedang gelisah."',
    },
  },
  {
    id: 'npc_cemetery_priest',
    name: 'Pastor Lucius',
    title: 'Pengusir Setan Pemakaman',
    affiliation: 'Ordo Salib Perak',
    role: 'healer',
    mood: 'Penuh Harapan & Taat',
    x: 1050,
    y: 140,
    direction: 'down',
    sprite: 'inquisitor',
    dialogueId: 'cemetery_priest_intro',
    voicePitch: 180,
    lore: 'Pendeta tua yang menjaga agar roh-roh jahat tidak keluar dari batas pemakaman.',
    portraitTheme: {
      primaryColor: '#eab308',
      accentColor: '#ca8a04',
      bgStyle: 'cemetery',
      headwear: 'Tudung Biarawan & Salib Suci',
      eyeGlowColor: '#fde047',
      quote: '"Cahaya kudus akan selalu menerangi jalanmu yang gelap."',
    },
  },
  {
    id: 'npc_cemetery_ghost',
    name: 'Arwah Prajurit Lupa Ingatan',
    title: 'Korban Perang Kutukan',
    affiliation: 'Pasukan Ravenfall yang Gugur',
    role: 'lore',
    mood: 'Bingung & Kesepian',
    x: 1150,
    y: 250,
    direction: 'left',
    sprite: 'ghost_knight',
    dialogueId: 'cemetery_ghost_intro',
    voicePitch: 200,
    lore: 'Arwah prajurit malang yang terikat pada dunianya karena tak ingat cara ia mati.',
    portraitTheme: {
      primaryColor: '#0ea5e9',
      accentColor: '#0284c7',
      bgStyle: 'cemetery',
      headwear: 'Helm Prajurit Berkarat Transparan',
      eyeGlowColor: '#7dd3fc',
      quote: '"Di mana... di mana pedangku? Mengapa terasa sangat dingin di sini?"',
    },
  },
  {
    id: 'npc_nun',
    name: 'Suster Genevieve',
    title: 'Biarawati Buta Pembawa Cahaya Suci',
    affiliation: 'Katedral Bulan Darah',
    role: 'healer',
    mood: 'Suci & Lembut',
    x: 300,
    y: 520,
    direction: 'down',
    sprite: 'nun',
    dialogueId: 'nun_intro',
    voicePitch: 420,
    lore: 'Meskipun matanya terpejam selamanya oleh sayatan cakar iblis, ia mampu melihat kemurnian jiwa setiap manusia.',
    portraitTheme: {
      primaryColor: '#38bdf8',
      accentColor: '#1e3a8a',
      bgStyle: 'cathedral',
      headwear: 'Kain Kafan Putih Penutup Mata & Salib Perak',
      eyeGlowColor: '#7dd3fc',
      quote: '"Dalam kegelapan yang paling pekat sekalipun, secercah doa suci takkan pernah padam."',
    },
  },
  {
    id: 'npc_bard',
    name: 'Aria sang Penyair Kegelapan',
    title: 'Pengembara Pembawa Biola Terkutuk',
    affiliation: 'Para Musisi Reruntuhan',
    role: 'lore',
    mood: 'Melankolis & Puitis',
    x: 940,
    y: 470,
    direction: 'right',
    sprite: 'bard',
    dialogueId: 'bard_intro',
    voicePitch: 340,
    lore: 'Membawa biola bersenar rambut peri malam, gesekan melodinya mengisahkan masa lalu raja-raja yang meminum darah.',
    portraitTheme: {
      primaryColor: '#a855f7',
      accentColor: '#581c87',
      bgStyle: 'ruins',
      headwear: 'Topi Baret Beludru Ungu dengan Bulu Gagak',
      eyeGlowColor: '#d8b4fe',
      quote: '"Dengarkanlah senar biolaku... setiap nada adalah ratapan jiwa yang tak sempat diselamatkan."',
    },
  },
  {
    id: 'npc_ghost_knight',
    name: 'Hantu Ksatria Godfrey',
    title: 'Roh Panglima Perang Salib Pertama',
    affiliation: 'Ksatria Salib Abadi',
    role: 'quest_giver',
    mood: 'Agung & Berduka',
    x: 1580,
    y: 190,
    direction: 'left',
    sprite: 'ghost_knight',
    dialogueId: 'ghost_knight_intro',
    voicePitch: 200,
    lore: 'Jasadnya terkubur di rawa berdarah ratusan tahun lalu, namun sumpahnya menjaga tanah ini tak pernah sirna.',
    portraitTheme: {
      primaryColor: '#2dd4bf',
      accentColor: '#134e4a',
      bgStyle: 'swamp',
      headwear: 'Helm Ksatria Besi Berlumut dengan Cahaya Biru Ethereal',
      eyeGlowColor: '#5eead4',
      quote: '"Ratusan tahun aku menanti seorang pewaris keberanian untuk menghabisi tiran kegelapan..."',
    },
  },
  {
    id: 'npc_eldrin',
    name: 'Eldrin si Alkemis Rawa',
    title: 'Ahli Ramuan Herbal & Racun Reruntuhan',
    affiliation: 'Klan Peri Hutan Jamur Rawa',
    role: 'alchemist',
    mood: 'Tenang & Eksentrik',
    x: 1420,
    y: 260,
    direction: 'down',
    sprite: 'eldrin',
    dialogueId: 'eldrin_intro',
    voicePitch: 310,
    lore: 'Peri rawa berambut zamrud yang meneliti getah rawa beracun dan memformulasikan belati beracun serta kantong ramuan penambah kelincahan.',
    portraitTheme: {
      primaryColor: '#10b981',
      accentColor: '#064e3b',
      bgStyle: 'swamp',
      headwear: 'Monokel Emas Alkemis & Jubah Sutra Lumut',
      eyeGlowColor: '#34d399',
      quote: '"Rawa ini tidak hanya membawa maut, pemburu... sari jamur darahnya menyimpan rahasia kecepatan tak terbatas."',
    },
  },
  {
    id: 'npc_seraphina',
    name: 'Seraphina si Boneka Gotik',
    title: 'Gadis Boneka Porselen Peramal Biara',
    affiliation: 'Pusaka Sakral Reruntuhan',
    role: 'oracle',
    mood: 'Misterius & Melankolis',
    x: 820,
    y: 490,
    direction: 'right',
    sprite: 'seraphina',
    dialogueId: 'seraphina_intro',
    voicePitch: 480,
    lore: 'Boneka porselen antik bermata rubi hidup yang bersenandung di antara pilar runtuh biara. Mengetahui takdir setiap jiwa di Ravenfall.',
    portraitTheme: {
      primaryColor: '#f43f5e',
      accentColor: '#4c0519',
      bgStyle: 'ruins',
      headwear: 'Pita Beludru Merah Mawar & Gaun Renda Lolita',
      eyeGlowColor: '#fb7185',
      quote: '"Detak jantung porselenku berbisik... pedangmu akan segera bermandikan darah sang penguasa kegelapan."',
    },
  },
  {
    id: 'npc_valerius',
    name: 'Valerius sang Pemburu Bayangan',
    title: 'Pemburu Naga Purba & Mercenary Kelabu',
    affiliation: 'Kelompok Tentara Bayaran Serigala',
    role: 'mercenary',
    mood: 'Dingin & Berani',
    x: 1540,
    y: 460,
    direction: 'left',
    sprite: 'valerius',
    dialogueId: 'valerius_intro',
    voicePitch: 210,
    lore: 'Pendekar bayaran yang menjelajahi Lembah Tulang Purba, memegang sabit bulan darah untuk menebas gerombolan kerangka.',
    portraitTheme: {
      primaryColor: '#64748b',
      accentColor: '#0f172a',
      bgStyle: 'ruins',
      headwear: 'Syal Bulu Serigala Hitam & Sabuk Senjata Ganda',
      eyeGlowColor: '#cbd5e1',
      quote: '"Kerangka-kerangka ini tak pernah lelah bangun kembali. Hanya bilah tajam yang bisa membungkam mereka selamanya."',
    },
  },
  {
    id: 'npc_roderick',
    name: 'Sir Roderick sang Templar Terbuang',
    title: 'Penjaga Benteng Salib Putih',
    affiliation: 'Ordo Suci Penjaga Segel',
    role: 'templar',
    mood: 'Kokoh & Pantang Menyerah',
    x: 240,
    y: 780,
    direction: 'up',
    sprite: 'roderick',
    dialogueId: 'roderick_intro',
    voicePitch: 190,
    lore: 'Ksatria berpelindung zirah baja tebal yang bersumpah menghentikan sekte vampir sebelum kutukan darah menyebar lebih jauh.',
    portraitTheme: {
      primaryColor: '#eab308',
      accentColor: '#713f12',
      bgStyle: 'cathedral',
      headwear: 'Helm Baja Bersalib Emas & Plat Pelindung Dada',
      eyeGlowColor: '#fde047',
      quote: '"Di balik gerbang ini mengalir air mancur berbau darah terkutuk. Rapatkan zirahmu pemburu, musuh kita bukan manusia!"',
    },
  },
  {
    id: 'npc_lilith',
    name: 'Putri Lilith si Vampir Cilik',
    title: 'Pewaris Takhta Kastil Drakula',
    affiliation: 'Keluarga Kerajaan Darah Abadi',
    role: 'princess',
    mood: 'Angkuh namun Menggemaskan',
    x: 1460,
    y: 920,
    direction: 'left',
    sprite: 'lilith',
    dialogueId: 'lilith_intro',
    voicePitch: 460,
    lore: 'Gadis vampir bergaun gotik dengan sayap kelelawar kecil di punggungnya. Suka bermalas-malasan di dekat takhta kastil kuno.',
    portraitTheme: {
      primaryColor: '#ec4899',
      accentColor: '#831843',
      bgStyle: 'crypt',
      headwear: 'Tiara Mawar Hitam & Sayap Kelelawar Mungil',
      eyeGlowColor: '#f472b6',
      quote: '"Hmph! Beraninya manusia kotor menginjak karpet kastil kakek buyutku tanpa membawakan manisan darah segar!"',
    },
  },
  {
    id: 'npc_celestine',
    name: 'Celestine sang Astrolog Malam',
    title: 'Penyihir Bintang Astral & Penjaga Observatorium',
    affiliation: 'Ordo Konstelasi Lilac',
    role: 'oracle',
    mood: 'Tenang & Berwawasan Kosmis',
    x: 280,
    y: 1220,
    direction: 'down',
    sprite: 'celestine',
    dialogueId: 'celestine_intro',
    voicePitch: 410,
    lore: 'Gadis penyihir berambut biru malam yang meneliti pergerakan rasi bintang di atas Ravenfall. Mengetahui bahwa kutukan gerhana bulan darah dapat dipatahkan dengan pusaka astral.',
    portraitTheme: {
      primaryColor: '#818cf8',
      accentColor: '#312e81',
      bgStyle: 'ruins',
      headwear: 'Tiara Kristal Bintang & Jubah Sutra Astral',
      eyeGlowColor: '#a5b4fc',
      quote: '"Bintang-bintang meramalkan kelahiran fajar baru... asalkan pedangmu tidak gentar menghadapi jurang kegelapan."',
    },
  },
  {
    id: 'npc_morrigan',
    name: 'Morrigan Ratu Gagak Hutan',
    title: 'Penyihir Bayangan & Penutur Bahasa Gagak',
    affiliation: 'Klan Rawa Terkutuk',
    role: 'lore',
    mood: 'Misterius & Mempesona',
    x: 1720,
    y: 220,
    direction: 'left',
    sprite: 'morrigan',
    dialogueId: 'morrigan_intro',
    voicePitch: 360,
    lore: 'Wanita misterius berselimutkan jubah bulu gagak hitam. Burung-burung gagak di dahan pohon rawa adalah mata dan telinganya di seluruh dunia.',
    portraitTheme: {
      primaryColor: '#6366f1',
      accentColor: '#1e1b4b',
      bgStyle: 'swamp',
      headwear: 'Mantel Bulu Gagak & Kalung Manik Onyx',
      eyeGlowColor: '#c7d2fe',
      quote: '"Gagak-gagakku melihatmu menembus kabut, pemburu... Hati-hati, tanah rawa ini haus akan darah segar."',
    },
  },
  {
    id: 'npc_noel',
    name: 'Noel sang Penjaga Gerbang',
    title: 'Squire Muda Penjaga Batas Reruntuhan',
    affiliation: 'Prajurit Pengawal Biara',
    role: 'guide',
    mood: 'Waspada & Bersemangat',
    x: 790,
    y: 450,
    direction: 'right',
    sprite: 'noel',
    dialogueId: 'noel_intro',
    voicePitch: 290,
    lore: 'Prajurit muda bersenjatakan tombak halberd yang setia menjaga gerbang masuk menuju reruntuhan biara dan lembah tulang.',
    portraitTheme: {
      primaryColor: '#38bdf8',
      accentColor: '#0c4a6e',
      bgStyle: 'ruins',
      headwear: 'Baret Baja Ringan & Syal Biru Langit',
      eyeGlowColor: '#7dd3fc',
      quote: '"Berhenti! Area di balik gerbang ini dipenuhi mayat hidup yang bangkit! Siapkan perlengkapanmu sebelum melangkah!"',
    },
  },
  {
    id: 'npc_elena',
    name: 'Elena sang Tabib Desa',
    title: 'Peramu Herbal & Penjaga Korban Kutukan',
    affiliation: 'Warga Penyintas Ravenfall',
    role: 'healer',
    mood: 'Lembut & Penuh Belas Kasih',
    x: 380,
    y: 260,
    direction: 'down',
    sprite: 'elena',
    dialogueId: 'elena_intro',
    voicePitch: 430,
    lore: 'Gadis tabib desa Ravenfall yang merawat para pemburu yang terluka. Ia meracik ramuan herbal penawar racun rawa dan salep pemulih stamina.',
    portraitTheme: {
      primaryColor: '#10b981',
      accentColor: '#064e3b',
      bgStyle: 'village',
      headwear: 'Bandana Herbal & Apron Tabib Putih',
      eyeGlowColor: '#6ee7b7',
      quote: '"Jangan paksakan dirimu jika terluka parah. Duduklah di sini, kubasuh lukamu dengan rebusan bunga mawar."',
    },
  },
  {
    id: 'npc_vladimir',
    name: 'Vladimir sang Pelayan Kastil',
    title: 'Kepala Pelayan Istana Drakula Berabad Abad',
    affiliation: 'Keluarga Kerajaan Darah Abadi',
    role: 'merchant',
    mood: 'Sopan & Dingin',
    x: 1560,
    y: 1220,
    direction: 'left',
    sprite: 'vladimir',
    dialogueId: 'vladimir_intro',
    voicePitch: 200,
    lore: 'Pelayan berjas tuksedo gotik antik yang menjaga kebun mawar hitam dan gudang pusaka keluarga bangsawan Drakula selama lebih dari 300 tahun.',
    portraitTheme: {
      primaryColor: '#f43f5e',
      accentColor: '#4c0519',
      bgStyle: 'crypt',
      headwear: 'Monokel Perak & Tuxedo Berkerah Mawar Hitam',
      eyeGlowColor: '#fda4af',
      quote: '"Selamat datang di Taman Mawar Hitam Yang Mulia. Apakah tuan pemburu mencari pusaka bangsawan malam?"',
    },
  },
];

export const INITIAL_OBJECTS: WorldObject[] = [
  // REALM GATES - Centered in every region / chunk (CHUNK_WIDTH = 640, CHUNK_HEIGHT = 360)
  // Row 0 (Y: 0 - 360, Center Y: 170)
  { id: 'gate_village', type: 'portal_gate', x: 320, y: 170, width: 48, height: 64, ySortOffset: 24, solid: true, name: 'Gerbang Suaka Desa Ravenfall' },
  { id: 'gate_cemetery', type: 'portal_gate', x: 960, y: 170, width: 48, height: 64, ySortOffset: 24, solid: true, name: 'Gerbang Makam Bulan Darah' },
  { id: 'gate_swamp', type: 'portal_gate', x: 1600, y: 170, width: 48, height: 64, ySortOffset: 24, solid: true, name: 'Gerbang Rawa Kabut Beracun' },
  // Row 1 (Y: 360 - 720, Center Y: 530)
  { id: 'gate_cathedral', type: 'portal_gate', x: 320, y: 530, width: 48, height: 64, ySortOffset: 24, solid: true, name: 'Gerbang Katedral Suci' },
  { id: 'gate_ruins', type: 'portal_gate', x: 960, y: 530, width: 48, height: 64, ySortOffset: 24, solid: true, name: 'Gerbang Menara Reruntuhan Bintang' },
  { id: 'gate_bone_valley', type: 'portal_gate', x: 1600, y: 530, width: 48, height: 64, ySortOffset: 24, solid: true, name: 'Gerbang Lembah Tulang Purba' },
  // Row 2 (Y: 720 - 1080, Center Y: 890)
  { id: 'gate_castle', type: 'portal_gate', x: 320, y: 890, width: 48, height: 64, ySortOffset: 24, solid: true, name: 'Gerbang Aula Takhta Kastil' },
  { id: 'gate_crypt', type: 'portal_gate', x: 960, y: 890, width: 48, height: 64, ySortOffset: 24, solid: true, name: 'Gerbang Labirin Kripta Kuno' },
  { id: 'gate_white_cross', type: 'portal_gate', x: 1600, y: 890, width: 48, height: 64, ySortOffset: 24, solid: true, name: 'Gerbang Benteng Salib Putih' },
  // Row 3 (Y: 1080 - 1440, Center Y: 1250)
  { id: 'gate_rose_garden', type: 'portal_gate', x: 320, y: 1250, width: 48, height: 64, ySortOffset: 24, solid: true, name: 'Gerbang Taman Mawar Hitam' },
  { id: 'gate_hellfire', type: 'portal_gate', x: 960, y: 1250, width: 48, height: 64, ySortOffset: 24, solid: true, name: 'Gerbang Api Neraka' },
  { id: 'gate_light_sanctuary', type: 'portal_gate', x: 1600, y: 1250, width: 48, height: 64, ySortOffset: 24, solid: true, name: 'Gerbang Suaka Cahaya Abadi' },
  // Chunk (0,0): Cursed Village Ravenfall
  {
    id: 'gothic_manor_1',
    type: 'gothic_house',
    x: 160,
    y: 90,
    width: 86,
    height: 70,
    ySortOffset: 28,
    solid: true,
    name: 'Rumah Bangsawan Kuno',
  },
  {
    id: 'gothic_manor_2',
    type: 'gothic_house',
    x: 460,
    y: 100,
    width: 80,
    height: 65,
    ySortOffset: 25,
    solid: true,
    name: 'Griya Terbengkalai',
  },
  {
    id: 'forge_anvil',
    type: 'anvil',
    x: 150,
    y: 240,
    width: 24,
    height: 22,
    ySortOffset: 8,
    solid: true,
    name: 'Paron Penempa Perak Viktor',
    lightRadius: 36,
    lightColor: 'rgba(249, 115, 22, 0.45)',
  },
  {
    id: 'gothic_tree_1',
    type: 'dead_tree',
    x: 70,
    y: 70,
    width: 38,
    height: 56,
    ySortOffset: 22,
    solid: true,
  },
  {
    id: 'gothic_tree_2',
    type: 'dead_tree',
    x: 530,
    y: 220,
    width: 38,
    height: 56,
    ySortOffset: 22,
    solid: true,
  },
  {
    id: 'lantern_g1',
    type: 'gothic_lantern',
    x: 210,
    y: 170,
    width: 16,
    height: 28,
    ySortOffset: 12,
    solid: true,
    lightRadius: 52,
    lightColor: 'rgba(234, 88, 12, 0.5)',
  },
  {
    id: 'lantern_g2',
    type: 'gothic_lantern',
    x: 370,
    y: 170,
    width: 16,
    height: 28,
    ySortOffset: 12,
    solid: true,
    lightRadius: 52,
    lightColor: 'rgba(234, 88, 12, 0.5)',
  },
  // Chunk (1,0): Haunted Cemetery (pixelX: 640 - 1280, pixelY: 0 - 360)
  { id: 'tomb_c1', type: 'tombstone', x: 710, y: 80, width: 20, height: 26, ySortOffset: 8, solid: true },
  { id: 'tomb_c2', type: 'tombstone', x: 790, y: 120, width: 20, height: 26, ySortOffset: 8, solid: true },
  { id: 'tomb_c3', type: 'tombstone', x: 920, y: 80, width: 20, height: 26, ySortOffset: 8, solid: true },
  { id: 'tomb_c4', type: 'tombstone', x: 1040, y: 140, width: 20, height: 26, ySortOffset: 8, solid: true },
  { id: 'mausoleum_1', type: 'mausoleum', x: 980, y: 80, width: 64, height: 55, ySortOffset: 22, solid: true, name: 'Mausoleum Keluarga Von Ravens' },
  { id: 'dead_tree_c1', type: 'dead_tree', x: 750, y: 220, width: 42, height: 60, ySortOffset: 24, solid: true },
  { id: 'dead_tree_c2', type: 'dead_tree', x: 1130, y: 180, width: 42, height: 60, ySortOffset: 24, solid: true },
  { id: 'lantern_cem', type: 'gothic_lantern', x: 840, y: 170, width: 16, height: 28, ySortOffset: 12, solid: true, lightRadius: 48, lightColor: 'rgba(56, 189, 248, 0.45)' },
  // Chunk (2,0): Blood Swamp & Crow Woods (pixelX: 1280 - 1920, pixelY: 0 - 360)
  { id: 'swamp_tree_1', type: 'dead_tree', x: 1360, y: 90, width: 44, height: 64, ySortOffset: 26, solid: true },
  { id: 'swamp_tree_2', type: 'dead_tree', x: 1510, y: 240, width: 44, height: 64, ySortOffset: 26, solid: true },
  { id: 'swamp_tree_3', type: 'dead_tree', x: 1750, y: 110, width: 44, height: 64, ySortOffset: 26, solid: true },
  { id: 'altar_godfrey', type: 'altar', x: 1680, y: 180, width: 36, height: 28, ySortOffset: 12, solid: true, name: 'Altar Penebusan Ksatria Godfrey', lightRadius: 50, lightColor: 'rgba(45, 212, 191, 0.5)' },
  // Chunk (0,1): Blood Cathedral (pixelX: 0 - 640, pixelY: 360 - 720)
  { id: 'cathedral_main', type: 'cathedral', x: 320, y: 400, width: 140, height: 110, ySortOffset: 45, solid: true, name: 'Katedral Bulan Darah (Façade Utama)' },
  { id: 'gargoyle_1', type: 'gargoyle', x: 230, y: 470, width: 24, height: 32, ySortOffset: 12, solid: true, name: 'Gargoyle Penjaga Katedral' },
  { id: 'gargoyle_2', type: 'gargoyle', x: 410, y: 470, width: 24, height: 32, ySortOffset: 12, solid: true, name: 'Gargoyle Penjaga Katedral' },
  { id: 'altar_cathedral', type: 'altar', x: 320, y: 595, width: 48, height: 32, ySortOffset: 12, solid: true, name: 'Altar Suci Persembahan Darah', lightRadius: 65, lightColor: 'rgba(239, 68, 68, 0.55)' },
  { id: 'lantern_cath_1', type: 'gothic_lantern', x: 270, y: 530, width: 16, height: 28, ySortOffset: 12, solid: true, lightRadius: 45, lightColor: 'rgba(251, 191, 36, 0.45)' },
  { id: 'lantern_cath_2', type: 'gothic_lantern', x: 370, y: 530, width: 16, height: 28, ySortOffset: 12, solid: true, lightRadius: 45, lightColor: 'rgba(251, 191, 36, 0.45)' },
  // Chunk (1,1): Ruined Abbey Gates (pixelX: 640 - 1280, pixelY: 360 - 720)
  { id: 'iron_fence_1', type: 'iron_fence', x: 720, y: 420, width: 90, height: 30, ySortOffset: 10, solid: true },
  { id: 'iron_fence_2', type: 'iron_fence', x: 890, y: 420, width: 90, height: 30, ySortOffset: 10, solid: true },
  { id: 'dead_tree_ruins', type: 'dead_tree', x: 1020, y: 480, width: 40, height: 60, ySortOffset: 24, solid: true },
  // Chunk (2,1): Valley of Ancient Bones (pixelX: 1280 - 1920, pixelY: 360 - 720)
  { id: 'bone_pile_1', type: 'bone_pile', x: 1390, y: 430, width: 50, height: 35, ySortOffset: 14, solid: true, name: 'Kerangka Naga Kuno' },
  { id: 'bone_pile_2', type: 'bone_pile', x: 1640, y: 510, width: 60, height: 40, ySortOffset: 16, solid: true, name: 'Timbunan Tulang Ksatria Gugur' },
  { id: 'dead_tree_bone', type: 'dead_tree', x: 1780, y: 450, width: 44, height: 64, ySortOffset: 26, solid: true },
  // Chunk (0,2): Vampire Coven Sanctum (pixelX: 0 - 640, pixelY: 720 - 1080)
  { id: 'blood_fountain_1', type: 'blood_fountain', x: 310, y: 840, width: 52, height: 45, ySortOffset: 18, solid: true, name: 'Air Mancur Darah Suci Sekte', lightRadius: 60, lightColor: 'rgba(225, 29, 72, 0.55)' },
  { id: 'gargoyle_coven_1', type: 'gargoyle', x: 210, y: 820, width: 24, height: 32, ySortOffset: 12, solid: true },
  { id: 'gargoyle_coven_2', type: 'gargoyle', x: 410, y: 820, width: 24, height: 32, ySortOffset: 12, solid: true },
  // Chunk (1,2): Crypt of the Lich King (pixelX: 640 - 1280, pixelY: 720 - 1080)
  { id: 'crypt_main_sarcophagus', type: 'crypt', x: 960, y: 800, width: 72, height: 50, ySortOffset: 20, solid: true, name: 'Sarkofagus Lord Malakar' },
  { id: 'altar_chalice', type: 'altar', x: 960, y: 970, width: 36, height: 28, ySortOffset: 12, solid: true, name: 'Pilar Penopang Piala Darah Abadi', lightRadius: 55, lightColor: 'rgba(168, 85, 247, 0.55)' },
  { id: 'lantern_crypt_1', type: 'gothic_lantern', x: 880, y: 860, width: 16, height: 28, ySortOffset: 12, solid: true, lightRadius: 46, lightColor: 'rgba(147, 51, 234, 0.5)' },
  { id: 'lantern_crypt_2', type: 'gothic_lantern', x: 1040, y: 860, width: 16, height: 28, ySortOffset: 12, solid: true, lightRadius: 46, lightColor: 'rgba(147, 51, 234, 0.5)' },
  // Chunk (2,2): Forgotten Castle Throne (pixelX: 1280 - 1920, pixelY: 720 - 1080)
  { id: 'dracula_throne', type: 'throne', x: 1600, y: 860, width: 48, height: 60, ySortOffset: 24, solid: true, name: 'Singgasana Besi Kastil Drakula', lightRadius: 65, lightColor: 'rgba(239, 68, 68, 0.6)' },
  { id: 'gargoyle_throne_1', type: 'gargoyle', x: 1520, y: 880, width: 24, height: 32, ySortOffset: 12, solid: true },
  { id: 'gargoyle_throne_2', type: 'gargoyle', x: 1680, y: 880, width: 24, height: 32, ySortOffset: 12, solid: true },
  // Chunk (0,3): Menara Bintang & Observatorium Lilac (pixelX: 0 - 640, pixelY: 1080 - 1440)
  { id: 'astral_telescope_main', type: 'astral_telescope', x: 320, y: 1180, width: 44, height: 52, ySortOffset: 20, solid: true, name: 'Teleskop Konstelasi Astral Kuno', lightRadius: 60, lightColor: 'rgba(129, 140, 248, 0.6)' },
  { id: 'lantern_astral_1', type: 'gothic_lantern', x: 230, y: 1220, width: 16, height: 28, ySortOffset: 12, solid: true, lightRadius: 48, lightColor: 'rgba(165, 180, 252, 0.5)' },
  { id: 'lantern_astral_2', type: 'gothic_lantern', x: 410, y: 1220, width: 16, height: 28, ySortOffset: 12, solid: true, lightRadius: 48, lightColor: 'rgba(165, 180, 252, 0.5)' },
  { id: 'altar_starlight', type: 'altar', x: 460, y: 1260, width: 36, height: 28, ySortOffset: 12, solid: true, name: 'Altar Bintang Jatuh', lightRadius: 48, lightColor: 'rgba(192, 132, 252, 0.5)' },
  // Chunk (1,3): Jurang Kegelapan Purba (Ancient Abyss Rift) (pixelX: 640 - 1280, pixelY: 1080 - 1440)
  { id: 'abyss_crystal_1', type: 'abyss_crystal', x: 960, y: 1200, width: 38, height: 50, ySortOffset: 18, solid: true, name: 'Kristal Nether Abyss Ungu', lightRadius: 68, lightColor: 'rgba(168, 85, 247, 0.65)' },
  { id: 'bone_pile_abyss', type: 'bone_pile', x: 820, y: 1250, width: 50, height: 35, ySortOffset: 14, solid: true, name: 'Kerangka Korban Jurang Nether' },
  // Chunk (2,3): Taman Mawar Hitam Terlarang (pixelX: 1280 - 1920, pixelY: 1080 - 1440)
  { id: 'rose_shrine_1', type: 'rose_shrine', x: 1600, y: 1190, width: 48, height: 54, ySortOffset: 20, solid: true, name: 'Monumen Mawar Hitam Terlarang', lightRadius: 60, lightColor: 'rgba(244, 63, 94, 0.6)' },
  { id: 'blood_fountain_garden', type: 'blood_fountain', x: 1440, y: 1250, width: 46, height: 40, ySortOffset: 16, solid: true, name: 'Air Mancur Mawar Vampir', lightRadius: 52, lightColor: 'rgba(225, 29, 72, 0.5)' },
];

export const INITIAL_ENEMIES: Enemy[] = [];

export const DIALOGUE_TREE: Record<string, DialogueNode> = {
  dungeon_guardian_dialogue: {
    speaker: 'Malaikat Penjaga Menara',
    speakerTitle: 'Pelindung Jiwa Lantai Menara',
    mood: 'holy',
    text: 'Selamat atas keberhasilanmu membersihkan lantai ini dari iblis kegelapan! Cahaya suci memberkatimu. Pilihlah bantuan yang kau butuhkan sebelum melangkah ke lantai berikutnya:',
    options: [
      { text: '💖 Memulihkan Seluruh Darah (Full Heal)', action: 'dungeon_full_heal', icon: '💖' },
      { text: '✨ Menerima Berkat Acak (Random Blessing)', action: 'dungeon_random_blessing', icon: '✨' },
      { text: '🏃 Lanjutkan Tanpa Bantuan', action: 'close_dialogue', icon: '🏃' },
    ],
  },
  trader_intro: {
    speaker: 'Ghazal',
    speakerTitle: 'Pedagang Misterius',
    mood: 'serious',
    text: 'Hehehe, apakah kau membutuhkan sesuatu yang kuat? Aku membawa ramuan dan intisari gelap yang tidak akan kau temukan di desa.',
    options: [
      { text: 'Beli Holy Potion (Memulihkan 100 HP) - 200 Gold', action: 'trade_holy_potion', icon: '🧪' },
      { text: 'Beli Shadow Essence (+10 Attack) - 500 Gold', action: 'trade_shadow_essence', icon: '🌑' },
      { text: 'Tidak, terima kasih.', action: 'close_dialogue', icon: '🏃' },
    ],
  },
  dialogue_only_cathedral: {
    speaker: 'Pengembara',
    speakerTitle: 'Jiwa Tanpa Arah',
    mood: 'eerie',
    text: 'Tempat ini sangat mengerikan... Aku tak tahu sudah berapa lama aku terjebak di sini. Tolong, berhati-hatilah.',
    options: [{ text: 'Semoga kau menemukan kedamaian.', action: 'close_dialogue' }],
  },
  dialogue_only_ruins: {
    speaker: 'Pengembara',
    speakerTitle: 'Jiwa Tanpa Arah',
    mood: 'eerie',
    text: 'Tempat ini sangat mengerikan... Aku tak tahu sudah berapa lama aku terjebak di sini. Tolong, berhati-hatilah.',
    options: [{ text: 'Semoga kau menemukan kedamaian.', action: 'close_dialogue' }],
  },
  dialogue_only_bone_valley: {
    speaker: 'Pengembara',
    speakerTitle: 'Jiwa Tanpa Arah',
    mood: 'eerie',
    text: 'Tempat ini sangat mengerikan... Aku tak tahu sudah berapa lama aku terjebak di sini. Tolong, berhati-hatilah.',
    options: [{ text: 'Semoga kau menemukan kedamaian.', action: 'close_dialogue' }],
  },
  dialogue_only_castle: {
    speaker: 'Pengembara',
    speakerTitle: 'Jiwa Tanpa Arah',
    mood: 'eerie',
    text: 'Tempat ini sangat mengerikan... Aku tak tahu sudah berapa lama aku terjebak di sini. Tolong, berhati-hatilah.',
    options: [{ text: 'Semoga kau menemukan kedamaian.', action: 'close_dialogue' }],
  },
  dialogue_only_crypt: {
    speaker: 'Pengembara',
    speakerTitle: 'Jiwa Tanpa Arah',
    mood: 'eerie',
    text: 'Tempat ini sangat mengerikan... Aku tak tahu sudah berapa lama aku terjebak di sini. Tolong, berhati-hatilah.',
    options: [{ text: 'Semoga kau menemukan kedamaian.', action: 'close_dialogue' }],
  },
  dialogue_only_white_cross: {
    speaker: 'Pengembara',
    speakerTitle: 'Jiwa Tanpa Arah',
    mood: 'eerie',
    text: 'Tempat ini sangat mengerikan... Aku tak tahu sudah berapa lama aku terjebak di sini. Tolong, berhati-hatilah.',
    options: [{ text: 'Semoga kau menemukan kedamaian.', action: 'close_dialogue' }],
  },
  dialogue_only_rose_garden: {
    speaker: 'Pengembara',
    speakerTitle: 'Jiwa Tanpa Arah',
    mood: 'eerie',
    text: 'Tempat ini sangat mengerikan... Aku tak tahu sudah berapa lama aku terjebak di sini. Tolong, berhati-hatilah.',
    options: [{ text: 'Semoga kau menemukan kedamaian.', action: 'close_dialogue' }],
  },
  dialogue_only_hellfire: {
    speaker: 'Pengembara',
    speakerTitle: 'Jiwa Tanpa Arah',
    mood: 'eerie',
    text: 'Tempat ini sangat mengerikan... Aku tak tahu sudah berapa lama aku terjebak di sini. Tolong, berhati-hatilah.',
    options: [{ text: 'Semoga kau menemukan kedamaian.', action: 'close_dialogue' }],
  },
  dialogue_only_light_sanctuary: {
    speaker: 'Pengembara',
    speakerTitle: 'Jiwa Tanpa Arah',
    mood: 'eerie',
    text: 'Tempat ini sangat mengerikan... Aku tak tahu sudah berapa lama aku terjebak di sini. Tolong, berhati-hatilah.',
    options: [{ text: 'Semoga kau menemukan kedamaian.', action: 'close_dialogue' }],
  },

  // 0. DUNGEON MASTER (Master Menara 100 Lantai)
  dungeon_master_intro: {
    speaker: 'Dungeon Master',
    speakerTitle: 'Penjaga Gerbang Menara 100 Lantai',
    mood: 'holy',
    text: 'Salam, Ksatria Berzirah Putih! Di hadapanmu berdiri Menara 100 Lantai—seluruh monster dan bos purba kini terkurung di dalamnya. Seluruh pertempuran dunia berpusat di dalam gerbang dimensi ini!',
    options: [
      { text: 'Masuki Menara 100 Lantai (Pilih / Lanjutkan Lantai)', nextId: 'dungeon_master_enter', action: 'open_dungeon_modal', icon: '🏰' },
      { text: 'Ambil Sumpah Penakluk Menara (+40% Damage vs Bos)', nextId: 'dungeon_master_oath', action: 'take_oath_dungeon_breaker', icon: '👑' },
      { text: 'Bagaimana struktur 100 lantai ini bekerja?', nextId: 'dungeon_master_explain', icon: '📜' },
      { text: 'Aku akan mempersiapkan perlengkapan terlebih dahulu.', nextId: 'dungeon_master_bye', icon: '🛡️' },
    ],
  },
  dungeon_master_enter: {
    speaker: 'Dungeon Master',
    speakerTitle: 'Penjaga Gerbang Menara 100 Lantai',
    mood: 'holy',
    text: 'Gerbang portal dimensi terbuka! Hadapi musuh setiap lantai dan bos perkasa di setiap 10 lantai untuk membuka skill tempur legendaris!',
    options: [{ text: 'Buka Menu Pemilihan Lantai Menara!', action: 'open_dungeon_modal', icon: '⚡' }],
  },
  dungeon_master_oath: {
    speaker: 'Dungeon Master',
    speakerTitle: 'Penjaga Gerbang Menara 100 Lantai',
    mood: 'holy',
    text: 'Sumpah Penakluk Menara telah terukir pada perisai putihmu! Kerusakanmu pada setiap Bos lantai menara meningkat +40%!',
    options: [{ text: 'Terima kasih, Master Menara!' }],
  },
  dungeon_master_explain: {
    speaker: 'Dungeon Master',
    speakerTitle: 'Penjaga Gerbang Menara 100 Lantai',
    mood: 'normal',
    text: 'Menara ini memiliki 100 lantai dengan 10 lingkungan unik yang berganti setiap 10 lantai: mulai dari Katakomba, Kripta Air, Gua Darah, Kawah Obsidian Api, hingga Takhta Cahaya Ilahi di Lantai 100! Setiap Bos lantai 10 akan menghadiahkan skill bertarung legendaris!',
    options: [{ text: 'Aku mengerti. Buka gerbangnya!', nextId: 'dungeon_master_enter' }],
  },
  dungeon_master_bye: {
    speaker: 'Dungeon Master',
    speakerTitle: 'Penjaga Gerbang Menara 100 Lantai',
    mood: 'normal',
    text: 'Gunakan area suaka ini untuk menempa bilah perak dan memperkuat zirahmu sebelum menantang menara.',
  },
  
  // 1. INKUISITOR BALTHAZAR
  inquisitor_intro: {
    speaker: 'Inkuisitor Balthazar',
    speakerTitle: 'Kepala Ordo Salib Perak',
    mood: 'serious',
    text: 'Terkutuklah malam ini... Gerhana Bulan Darah telah membangkitkan para mayat dari liang lahat!',
    options: [
      { text: 'Apa yang bisa kulakukan untuk menghentikannya?', nextId: 'inquisitor_quest_detail', icon: '⚔️' },
      { text: 'Siapakah engkau sebenarnya, pemburu tua?', nextId: 'inquisitor_who', icon: '🛡️' },
      { text: 'Berikan aku nasehat bertahan hidup.', nextId: 'inquisitor_tips', icon: '📜' },
    ],
  },
  inquisitor_who: {
    speaker: 'Inkuisitor Balthazar',
    speakerTitle: 'Kepala Ordo Salib Perak',
    mood: 'serious',
    text: 'Aku adalah pelindung terakhir ordo suci di Ravenfall. Bilah perakku telah menumpahkan ribuan darah iblis dan memenggal ratusan lich purba.',
    options: [{ text: 'Beri aku tugas suci ini!', nextId: 'inquisitor_quest_detail', icon: '⚔️' }],
  },
  inquisitor_tips: {
    speaker: 'Inkuisitor Balthazar',
    speakerTitle: 'Kepala Ordo Salib Perak',
    mood: 'normal',
    text: 'Temui Viktor di bengkel barat desa untuk menempa bilah perakmu. Mintalah doa Suster Genevieve di Katedral Selatan untuk melipatgandakan daya tahanmu!',
    options: [{ text: 'Terima kasih, petunjuk ini sangat berharga.', nextId: 'inquisitor_intro' }],
  },
  inquisitor_quest_detail: {
    speaker: 'Inkuisitor Balthazar',
    speakerTitle: 'Kepala Ordo Salib Perak',
    mood: 'serious',
    text: 'Lord Malakar telah membangkitkan "Piala Darah Abadi" di kedalaman Ruang Bawah Tanah Kuno (Sektor Selatan Tengah). Hancurkan kekuatannya dan bawa piala itu kemari!',
    options: [
      { text: 'Demi keselamatan Ravenfall, aku bersumpah!', nextId: 'inquisitor_quest_accepted', action: 'give_quest', icon: '⚔️' },
      { text: 'Monster di sana terlalu mengerikan bagiku...', nextId: 'inquisitor_encourage', icon: '🛡️' },
    ],
  },
  inquisitor_quest_accepted: {
    speaker: 'Inkuisitor Balthazar',
    speakerTitle: 'Kepala Ordo Salib Perak',
    mood: 'holy',
    text: 'Gunakan pedang perakmu dan tebas sebelum mereka mendekat! Manfaatkan manuver Dash [B / Spasi] untuk menghindari serangan sihir es mereka!',
    options: [{ text: 'Bilah perakku siap menghabisi mereka!', icon: '⚔️' }],
  },
  inquisitor_quest_check: {
    speaker: 'Inkuisitor Balthazar',
    speakerTitle: 'Kepala Ordo Salib Perak',
    mood: 'serious',
    text: 'Apakah engkau telah merebut kembali Piala Darah dari cengkeraman Lord Malakar di Ruang Bawah Tanah?',
    options: [
      { text: 'Ini dia, Inkuisitor! Lord Malakar telah kubinasakan!', nextId: 'inquisitor_quest_complete', action: 'complete_quest', icon: '🏆' },
      { text: 'Aku masih harus bersiap menghadapi pasukan kegelapannya.', nextId: 'inquisitor_keep_trying', icon: '🛡️' },
    ],
  },
  inquisitor_quest_complete: {
    speaker: 'Inkuisitor Balthazar',
    speakerTitle: 'Kepala Ordo Salib Perak',
    mood: 'holy',
    text: 'Terpujilah keberanianmu! Kutukan Bulan Darah mulai pudar dari tanah Ravenfall! Terimalah 150 keping emas dan anugerah gelar Pemburu Kegelapan!',
    options: [{ text: 'Sebuah kehormatan membasmi kegelapan ini!', icon: '🏆' }],
  },
  inquisitor_encourage: {
    speaker: 'Inkuisitor Balthazar',
    speakerTitle: 'Kepala Ordo Salib Perak',
    mood: 'serious',
    text: 'Ketakutan adalah makanan para iblis! Mintalah bekal ramuan darah dari Lady Carmilla sebelum melangkah ke pemakaman!',
    options: [{ text: 'Baiklah, aku terima tugas suci ini!', nextId: 'inquisitor_quest_accepted', action: 'give_quest', icon: '⚔️' }],
  },
  inquisitor_keep_trying: {
    speaker: 'Inkuisitor Balthazar',
    speakerTitle: 'Kepala Ordo Salib Perak',
    mood: 'normal',
    text: 'Waspadalah terhadap sihir es Lord Malakar. Segera minum ramuan darah [Q] bila HP Anda menurun drastis.',
    options: [{ text: 'Aku akan berhati-hati.' }],
  },
  // 2. LADY CARMILLA
  carmilla_intro: {
    speaker: 'Lady Carmilla',
    speakerTitle: 'Bangsawan Darah Terkutuk',
    mood: 'mysterious',
    text: 'Selamat malam, pemburu tampan... Mencari sari darah murni untuk menyegarkan urat nadimu di malam yang dingin ini?',
    options: [
      { text: 'Beli Elixir Darah Vampir (30 Gold)', nextId: 'carmilla_buy_elixir', action: 'open_shop', icon: '🧪' },
      { text: 'Sembuhkan luka-lukaku dengan sihir darahmu!', nextId: 'carmilla_heal', action: 'heal', icon: '💖' },
      { text: 'Ceritakan rahasia tentang Klan Bayangan Malam.', nextId: 'carmilla_lore', icon: '📖' },
      { text: 'Aku harus segera bergegas.', nextId: 'carmilla_bye', icon: '🚪' },
    ],
  },
  carmilla_buy_elixir: {
    speaker: 'Lady Carmilla',
    speakerTitle: 'Bangsawan Darah Terkutuk',
    mood: 'mysterious',
    text: 'Nikmatilah setiap tetes sari merah ini... Niscaya tubuhmu akan diselimuti kekuatan gaib yang tak terpatahkan.',
    options: [{ text: 'Terima kasih, Carmilla.' }],
  },
  carmilla_heal: {
    speaker: 'Lady Carmilla',
    speakerTitle: 'Bangsawan Darah Terkutuk',
    mood: 'mysterious',
    text: 'Mendekatlah ke arah cadarku... Biarkan mantra darah memulihkan setiap retak tulang dan lukamu secara instan!',
    options: [{ text: 'Luar biasa... Tubuhku pulih total!' }],
  },
  carmilla_lore: {
    speaker: 'Lady Carmilla',
    speakerTitle: 'Bangsawan Darah Terkutuk',
    mood: 'eerie',
    text: 'Dahulu kala, raja negeri ini menolak kematian dan membuat perjanjian dengan gerhana bulan. Di ujung tenggara dunia ini, singgasananya masih berdiri sunyi...',
    options: [{ text: 'Kastil Drakula di ujung tenggara?', nextId: 'carmilla_castle_lore' }],
  },
  carmilla_castle_lore: {
    speaker: 'Lady Carmilla',
    speakerTitle: 'Bangsawan Darah Terkutuk',
    mood: 'eerie',
    text: 'Ya, Tahta Terbengkalai. Di sana tersimpan pusaka tertua bangsa kami, dijaga oleh bayangan sang raja sendiri.',
    options: [{ text: 'Aku akan membuktikannya nanti.' }],
  },
  carmilla_bye: {
    speaker: 'Lady Carmilla',
    speakerTitle: 'Bangsawan Darah Terkutuk',
    mood: 'mysterious',
    text: 'Jangan biarkan dirimu mati terlalu cepat... Aku menyukai mereka yang mampu bertahan di kegelapan.',
  },
  // 3. VIKTOR PANDAI BESI
  blacksmith_intro: {
    speaker: 'Viktor sang Pandai Besi',
    speakerTitle: 'Penempa Senjata Perak & Zirah Putih',
    mood: 'grumpy',
    text: 'Dentang paluku tak pernah berhenti! Di sini kamu bisa memperkuat bilah perak, menyepuh Zirah Putih Ksatria, dan mengikrarkan Sumpah Suci!',
    options: [
      { text: 'Buka Bengkel Enchanting & Sumpah Suci', action: 'open_enchanting_modal', icon: '✨' },
      { text: 'Tempa Pedang Perak (+8 ATK) seharga 60 Gold', nextId: 'blacksmith_upgrade', action: 'upgrade_weapon', icon: '🔨' },
      { text: 'Bagaimana cara membuat senjata paling ampuh melawan monster menara?', nextId: 'blacksmith_lore', icon: '📖' },
      { text: 'Hanya melihat-lihat perapianmu.', nextId: 'blacksmith_bye', icon: '🚪' },
    ],
  },
  blacksmith_upgrade: {
    speaker: 'Viktor sang Pandai Besi',
    speakerTitle: 'Penempa Senjata Perak',
    mood: 'holy',
    text: 'CLANG! CLANG! Selesai! Bilah perakmu kini dilapisi intisari suci api abadi. Tak ada mayat hidup yang mampu menahan tebasan ini!',
    options: [{ text: 'Pedang ini luar biasa tajam!' }],
  },
  blacksmith_lore: {
    speaker: 'Viktor sang Pandai Besi',
    speakerTitle: 'Penempa Senjata Perak',
    mood: 'serious',
    text: 'Besi biasa hanya menggelitik kulit mereka. Hanya perak yang disepuh bara suci dan abu tulang kuno yang sanggup membakar jantung vampir.',
    options: [{ text: 'Aku mengerti sekarang.' }],
  },
  blacksmith_bye: {
    speaker: 'Viktor sang Pandai Besi',
    speakerTitle: 'Penempa Senjata Perak',
    mood: 'grumpy',
    text: 'Jaga pedangmu tetap tajam, atau lehermu yang akan menjadi sarung taring mereka!',
  },
  // NEW NPCS: CEMETERY
  cemetery_priest_intro: {
    speaker: 'Pastor Lucius',
    speakerTitle: 'Pengusir Setan Pemakaman',
    mood: 'holy',
    text: 'Cahaya salib membimbing langkahmu, Anakku. Tempat ini dipenuhi kutukan, namun iman yang kuat tak akan pernah goyah.',
    options: [
      { text: 'Berikan aku berkat cahaya suci.', nextId: 'cemetery_priest_blessing', action: 'cemetery_blessing', icon: '✨' },
      { text: 'Terima kasih atas doamu, Pastor.', action: 'close_dialogue', icon: '🙏' },
    ],
  },
  cemetery_priest_blessing: {
    speaker: 'Pastor Lucius',
    speakerTitle: 'Pengusir Setan Pemakaman',
    mood: 'holy',
    text: 'Tuhan semesta alam menyertaimu. Rasakan kehangatan suci ini mengalir di nadimu (+15 Max HP)!',
    options: [{ text: 'Tubuhku terasa lebih bugar!', action: 'close_dialogue', icon: '💪' }],
  },
  cemetery_ghost_intro: {
    speaker: 'Arwah Prajurit',
    speakerTitle: 'Korban Perang Kutukan',
    mood: 'eerie',
    text: 'Dingin... Kenapa tempat ini sangat dingin? Aku... tidak ingat rumahku. Aku hanya ingat panji gagak hitam yang berkibar sebelum gelap.',
    options: [
      { text: 'Kau sudah tiada, istirahatlah dengan tenang.', nextId: 'cemetery_ghost_peace', icon: '🕊️' },
      { text: 'Semoga kau menemukan kedamaianmu.', action: 'close_dialogue', icon: '🏃' },
    ],
  },
  cemetery_ghost_peace: {
    speaker: 'Arwah Prajurit',
    speakerTitle: 'Korban Perang Kutukan',
    mood: 'eerie',
    text: 'Tiada... jadi peperangan sudah berakhir? (Sosok itu perlahan memudar ke dalam kabut malam)',
    options: [{ text: 'Beristirahatlah, prajurit.', action: 'close_dialogue' }],
  },

  // 4. MORGATH PENJAGA KUBUR
  gravekeeper_intro: {
    speaker: 'Morgath si Penjaga Kubur',
    speakerTitle: 'Penggali Makam Kuno',
    mood: 'eerie',
    text: 'Sssttt... Jangan bicara terlalu keras! Makam-makam di sini mendengarkan setiap hembusan nafasmu.',
    options: [
      { text: 'Mengapa tanah pemakaman ini sangat berkabut?', nextId: 'gravekeeper_mist', icon: '🌫️' },
      { text: 'Beri aku air suci untuk menangkal kutukan makam.', nextId: 'gravekeeper_gift', action: 'heal', icon: '💧' },
      { text: 'Hanya lewat, pak tua.', nextId: 'gravekeeper_bye', icon: '🚪' },
    ],
  },
  gravekeeper_mist: {
    speaker: 'Morgath si Penjaga Kubur',
    speakerTitle: 'Penggali Makam Kuno',
    mood: 'eerie',
    text: 'Kabut ini adalah nafas orang-orang mati yang jiwanya terikat pada gerhana bulan darah. Bila kau menjelajah ke timur, kau akan sampai di Rawa Darah.',
    options: [{ text: 'Rawa Darah? Siapa yang ada di sana?', nextId: 'gravekeeper_swamp' }],
  },
  gravekeeper_swamp: {
    speaker: 'Morgath si Penjaga Kubur',
    speakerTitle: 'Penggali Makam Kuno',
    mood: 'serious',
    text: 'Arwah Ksatria Godfrey masih melayang di antara pepohonan mati rawa itu, mencari cincin dan pedangnya yang hilang ratusan tahun lalu.',
    options: [{ text: 'Aku akan mencarinya.' }],
  },
  gravekeeper_gift: {
    speaker: 'Morgath si Penjaga Kubur',
    speakerTitle: 'Penggali Makam Kuno',
    mood: 'holy',
    text: 'Ini, basuhlah keningmu dengan air suci dari sumur makam tertua. Darahmu akan kembali tenang.',
    options: [{ text: 'Terima kasih atas kebaikanmu, Morgath.' }],
  },
  gravekeeper_bye: {
    speaker: 'Morgath si Penjaga Kubur',
    speakerTitle: 'Penggali Makam Kuno',
    mood: 'eerie',
    text: 'Hati-hati melangkah... jangan sampai kau terperosok ke liang kubur yang baru saja kugali.',
  },
  // 5. SUSTER GENEVIEVE
  nun_intro: {
    speaker: 'Suster Genevieve',
    speakerTitle: 'Biarawati Buta Pembawa Cahaya Suci',
    mood: 'holy',
    text: 'Salam sejahtera, pengembara berhati tabah... Walau mataku buta, aku dapat mendengar degup jantungmu yang berani menantang malam terkutuk ini.',
    options: [
      { text: 'Berikan aku berkat suci pelindung katedral!', nextId: 'nun_blessing', action: 'blessing', icon: '✨' },
      { text: 'Sembuhkan luka-luka di tubuhku dengan doa suci.', nextId: 'nun_heal', action: 'heal', icon: '💖' },
      { text: 'Apa yang terjadi pada katedral megah ini?', nextId: 'nun_history', icon: '⛪' },
      { text: 'Doakan perjalananku, suster.', nextId: 'nun_bye', icon: '🕊️' },
    ],
  },
  nun_blessing: {
    speaker: 'Suster Genevieve',
    speakerTitle: 'Biarawati Buta Pembawa Cahaya Suci',
    mood: 'holy',
    text: 'Terimalah Tasbih Suci ini... Semoga air mata para martir menaungi jiwamu, meningkatkan batas maksimal darahmu (+25 Max HP)!',
    options: [{ text: 'Aku merasakan kehangatan suci merasuki ragaku!' }],
  },
  nun_heal: {
    speaker: 'Suster Genevieve',
    speakerTitle: 'Biarawati Buta Pembawa Cahaya Suci',
    mood: 'holy',
    text: '"Tuhan ordo perak, basuhlah luka pejuang ini..." Tubuhmu diselimuti pendar cahaya keemasan. Seluruh HP-mu pulih sempurna!',
    options: [{ text: 'Terima kasih banyak, Suster Genevieve.' }],
  },
  nun_history: {
    speaker: 'Suster Genevieve',
    speakerTitle: 'Biarawati Buta Pembawa Cahaya Suci',
    mood: 'serious',
    text: 'Katedral ini pernah menjadi benteng cahaya terkuat. Namun ketika Lord Malakar mengorbankan piala darah di kuil selatan, kegelapan merayap meracuni altar suci ini.',
    options: [{ text: 'Aku akan merebut kembali piala itu demi katedral ini!' }],
  },
  nun_bye: {
    speaker: 'Suster Genevieve',
    speakerTitle: 'Biarawati Buta Pembawa Cahaya Suci',
    mood: 'holy',
    text: 'Pergilah dalam lindungan cahaya. Jangan biarkan keraguan meredupkan pedangmu.',
  },
  // 6. ARIA SANG PENYAIR
  bard_intro: {
    speaker: 'Aria sang Penyair Kegelapan',
    speakerTitle: 'Pengembara Pembawa Biola',
    mood: 'poetic',
    text: '~ 🎵 Biola bergesek di bawah bulan merah, mayat berbaris menginjak tanah berdarah... 🎵 ~ Ah, selamat malam penonton tunggalku!',
    options: [
      { text: 'Lagu apa yang sedang engkau mainkan, nona?', nextId: 'bard_song', icon: '🎻' },
      { text: 'Apakah engkau tahu rahasia Lembah Tulang di timur?', nextId: 'bard_bone_valley', icon: '💀' },
      { text: 'Beri aku semangat untuk melawan mimpi buruk ini.', nextId: 'bard_buff', action: 'heal', icon: '✨' },
    ],
  },
  bard_song: {
    speaker: 'Aria sang Penyair Kegelapan',
    speakerTitle: 'Pengembara Pembawa Biola',
    mood: 'poetic',
    text: 'Ini adalah "Requiem of the Damned". Lagu pengantar tidur untuk mereka yang mati namun menolak terpejam. Melodinya menjaga akal sehatku di tengah reruntuhan ini.',
    options: [{ text: 'Alunan yang sungguh menghanyutkan jiwa.' }],
  },
  bard_bone_valley: {
    speaker: 'Aria sang Penyair Kegelapan',
    speakerTitle: 'Pengembara Pembawa Biola',
    mood: 'eerie',
    text: 'Lembah Tulang adalah tempat jatuhnya ribuan ksatria dalam Perang Salib Kuno. Di sana terserak tulang raksasa dan peti-peti yang terlupakan.',
    options: [{ text: 'Aku harus berhati-hati saat melintasinya.' }],
  },
  bard_buff: {
    speaker: 'Aria sang Penyair Kegelapan',
    speakerTitle: 'Pengembara Pembawa Biola',
    mood: 'poetic',
    text: '~ 🎵 Tabahkan hatimu wahai pahlawan malam, pedangmu bersinar menghalau kelam! 🎵 ~ Alunan biolaku mengembalikan kebugaranmu!',
    options: [{ text: 'Terima kasih, Aria!' }],
  },
  // 7. HANTU KSATRIA GODFREY
  ghost_knight_intro: {
    speaker: 'Hantu Ksatria Godfrey',
    speakerTitle: 'Roh Panglima Perang Salib Pertama',
    mood: 'eerie',
    text: 'Siapa yang berani mengusik tidur abadiku di rawa berkabut ini... Tubuhmu memancarkan tekad seorang kesatria sejati.',
    options: [
      { text: 'Aku pemburu yang bersumpah membebaskan Ravenfall dari kutukan.', nextId: 'ghost_crusade', icon: '⚔️' },
      { text: 'Mengapa rohmu masih terikat di rawa ini, Panglima?', nextId: 'ghost_lore', icon: '🛡️' },
      { text: 'Berikan aku warisan kekuatan perangmu!', nextId: 'ghost_ring', action: 'blessing', icon: '💍' },
    ],
  },
  ghost_crusade: {
    speaker: 'Hantu Ksatria Godfrey',
    speakerTitle: 'Roh Panglima Perang Salib Pertama',
    mood: 'holy',
    text: 'Bagus! Api perjuangan belum padam! Basmilah mayat-mayat hidup di Lembah Tulang dan hancurkan Lord Malakar di kedalaman Ruang Bawah Tanah!',
    options: [{ text: 'Akan kulaksanakan sumpah ini!' }],
  },
  ghost_lore: {
    speaker: 'Hantu Ksatria Godfrey',
    speakerTitle: 'Roh Panglima Perang Salib Pertama',
    mood: 'serious',
    text: 'Aku dikhianati oleh sekte vampir dalam pertempuran terakhir. Jasadku tenggelam, namun jiwaku takkan tenang sebelum raja kegelapan musnah.',
    options: [{ text: 'Dendammu akan segera terbalaskan.' }],
  },
  ghost_ring: {
    speaker: 'Hantu Ksatria Godfrey',
    speakerTitle: 'Roh Panglima Perang Salib Pertama',
    mood: 'holy',
    text: 'Ambillah Cincin Ksatria Godfrey di dalam peti rawa di dekatku (+8 ATK). Semoga arwah para leluhur menuntun tebasan pedangmu!',
    options: [{ text: 'Aku menerimanya dengan penuh hormat.' }],
  },
  // 8. ELDRIN SI ALKEMIS RAWA
  eldrin_intro: {
    speaker: 'Eldrin si Alkemis Rawa',
    speakerTitle: 'Ahli Ramuan Herbal & Racun Reruntuhan',
    mood: 'mysterious',
    text: 'Ah... seorang pemburu yang selamat menembus kabut beracun. Sedang mencari penangkal racun, ataukah racun yang lebih mematikan dari gigitan vampir?',
    options: [
      { text: 'Ramuan apa yang kau racik di tengah rawa ini?', nextId: 'eldrin_lore', icon: '🧪' },
      { text: 'Beli Belati Racun Bayangan (120 Gold)', nextId: 'eldrin_shop', action: 'buy_stiletto', icon: '🗡️' },
      { text: 'Berikan aku ramuan pemulih kelincahan kaki!', nextId: 'eldrin_gift', action: 'blessing', icon: '🌿' },
    ],
  },
  eldrin_lore: {
    speaker: 'Eldrin si Alkemis Rawa',
    speakerTitle: 'Ahli Ramuan Herbal & Racun Reruntuhan',
    mood: 'mysterious',
    text: 'Getah jamur ungu rawa ini bereaksi dengan darah kelelawar vampir. Dengan ekstraksi yang tepat, aku bisa menempa Belati Racun Rawa (+18 ATK, +20 SPD) yang sangat ringan.',
    options: [{ text: 'Sangat mengagumkan sekaligus berbahaya.' }],
  },
  eldrin_shop: {
    speaker: 'Eldrin si Alkemis Rawa',
    speakerTitle: 'Ahli Ramuan Herbal & Racun Reruntuhan',
    mood: 'normal',
    text: 'Periksalah kantong ramuanku. Belati Racun dan Kantong Alkimia peningkat kecepatan tersedia jika kau memiliki cukup emas.',
    options: [{ text: 'Terima kasih atas informasinya, Eldrin!' }],
  },
  eldrin_gift: {
    speaker: 'Eldrin si Alkemis Rawa',
    speakerTitle: 'Ahli Ramuan Herbal & Racun Reruntuhan',
    mood: 'mysterious',
    text: 'Kuhirupkan sari spora herbal suci ke dalam jubahmu. Kakimu kini bergerak seringan embun pagi (+Speed Blessing)!',
    options: [{ text: 'Terima kasih, Eldrin!' }],
  },
  // 9. SERAPHINA SI BONEKA GOTIK
  seraphina_intro: {
    speaker: 'Seraphina si Boneka Gotik',
    speakerTitle: 'Gadis Boneka Porselen Peramal Biara',
    mood: 'eerie',
    text: 'Tik... tok... Jarum jam kematian berputar di langit Ravenfall. Apakah engkau datang untuk memutar kunci di punggungku, pemburu?',
    options: [
      { text: 'Siapa yang menciptakanmu di tempat runtuh ini?', nextId: 'seraphina_origin', icon: '🪆' },
      { text: 'Ramalkan takdir pertarunganku melawan Lord Malakar!', nextId: 'seraphina_prophecy', icon: '🔮' },
      { text: 'Gaun sutra berenda itu... apakah bisa kupelajari sihirnya?', nextId: 'seraphina_dress', icon: '👗' },
    ],
  },
  seraphina_origin: {
    speaker: 'Seraphina si Boneka Gotik',
    speakerTitle: 'Gadis Boneka Porselen Peramal Biara',
    mood: 'mysterious',
    text: 'Uskup agung biara ini memahat wajahku dari porselen salib sebelum ia dibantai oleh pasukan vampir. Air matanya menetes ke mataku, memberiku napas keabadian.',
    options: [{ text: 'Kisah masa lalu yang pilu...' }],
  },
  seraphina_prophecy: {
    speaker: 'Seraphina si Boneka Gotik',
    speakerTitle: 'Gadis Boneka Porselen Peramal Biara',
    mood: 'eerie',
    text: 'Kulihat kilatan pedang perak terhunus di ruang bawah tanah. Malakar takkan mati oleh senjata biasa; hanya tebasan suci yang diiringi tekad baja yang dapat memecahkan tengkoraknya!',
    options: [{ text: 'Ramalanmu akan kujadikan penuntun pedangku.' }],
  },
  seraphina_dress: {
    speaker: 'Seraphina si Boneka Gotik',
    speakerTitle: 'Gadis Boneka Porselen Peramal Biara',
    mood: 'normal',
    text: 'Gaun Sutra Hitam Berenda (+3 DEF, +35 HP, +8 ATK) di dalam peti runtuhan biara dapat melindungimu dari cengkeraman arwah penasaran.',
    options: [{ text: 'Akan kucari gaun pusaka itu!' }],
  },
  // 10. VALERIUS SANG PEMBURU BAYANGAN
  valerius_intro: {
    speaker: 'Valerius sang Pemburu Bayangan',
    speakerTitle: 'Pemburu Naga Purba & Mercenary',
    mood: 'serious',
    text: 'Berhenti di sana. Lembah Tulang bukan tempat bermain anak ingusan. Melangkah tiga langkah lagi, seratus kerangka bersenjata panah akan mengincar jantungmu.',
    options: [
      { text: 'Aku bukan penakut. Aku pemburu Ravenfall yang sejati.', nextId: 'valerius_respect', icon: '🐺' },
      { text: 'Senjata raksasa apa yang kau pikul itu?', nextId: 'valerius_weapon', icon: '🗡️' },
      { text: 'Apakah engkau punya perbekalan zirah cadangan?', nextId: 'valerius_armor', icon: '🛡️' },
    ],
  },
  valerius_respect: {
    speaker: 'Valerius sang Pemburu Bayangan',
    speakerTitle: 'Pemburu Naga Purba & Mercenary',
    mood: 'serious',
    text: 'Sorot matamu membuktikan kau bukan pembual. Jika kau berhasil menembus gua mayat di timur laut, kau berhak menyandang gelar Penakluk Malam.',
    options: [{ text: 'Akan kubuktikan kemampuanku kepadamu.' }],
  },
  valerius_weapon: {
    speaker: 'Valerius sang Pemburu Bayangan',
    speakerTitle: 'Pemburu Naga Purba & Mercenary',
    mood: 'serious',
    text: 'Ini Sabit Bulan Darah (+35 ATK, +15 SPD). Kutempa dari taring naga kuno dan disepuh darah bangsawan coven. Sekali tebas, lima kepala tengkorak melayang.',
    options: [{ text: 'Daya hancur yang luar biasa!' }],
  },
  valerius_armor: {
    speaker: 'Valerius sang Pemburu Bayangan',
    speakerTitle: 'Pemburu Naga Purba & Mercenary',
    mood: 'normal',
    text: 'Gunakan Mantel Kulit Pemburu Gagak (+4 DEF, +30 HP). Mantel ini ringan dan tidak memperlambat refleks menghindarmu.',
    options: [{ text: 'Saran yang sangat berguna.' }],
  },
  // 11. SIR RODERICK SANG TEMPLAR
  roderick_intro: {
    speaker: 'Sir Roderick sang Templar Terbuang',
    speakerTitle: 'Penjaga Benteng Salib Putih',
    mood: 'holy',
    text: 'Demi cahaya suci! Jangan mendekati air mancur darah itu! Para penganut sekte vampir sedang menyiapkan ritual pengorbanan jiwa!',
    options: [
      { text: 'Ksatria agung, mari kita serang sarang mereka bersama!', nextId: 'roderick_crusade', icon: '⚔️' },
      { text: 'Bagaimana caraku menahan serangan mematikan mereka?', nextId: 'roderick_defense', icon: '🛡️' },
      { text: 'Berikan aku restu perlindungan templar.', nextId: 'roderick_blessing', action: 'heal', icon: '✨' },
    ],
  },
  roderick_crusade: {
    speaker: 'Sir Roderick sang Templar Terbuang',
    speakerTitle: 'Penjaga Benteng Salib Putih',
    mood: 'holy',
    text: 'Pedangku siap mendampingimu! Zirah Templar yang kupakai telah menahan ratusan gigitan vampir. Kenakan perlengkapan pelindung yang kokoh sebelum melangkah masuk!',
    options: [{ text: 'Maju demi kehormatan ordo!' }],
  },
  roderick_defense: {
    speaker: 'Sir Roderick sang Templar Terbuang',
    speakerTitle: 'Penjaga Benteng Salib Putih',
    mood: 'serious',
    text: 'Zirah Besi Ksatria Templar (+8 DEF, +50 HP) memberikan pertahanan baja tertinggi. Kamu bisa menemukannya di peti harta sekte atau menempanya dari logam perak.',
    options: [{ text: 'Aku membutuhkan pertahanan sekuat itu.' }],
  },
  roderick_blessing: {
    speaker: 'Sir Roderick sang Templar Terbuang',
    speakerTitle: 'Penjaga Benteng Salib Putih',
    mood: 'holy',
    text: 'Kusalibkan lambang cahaya ke perisaimu. Pulihkan luka-lukamu dan berdiri tegaklah kembali!',
    options: [{ text: 'Terima kasih, Ksatria Roderick!' }],
  },
  // 12. PUTRI LILITH SI VAMPIR CILIK
  lilith_intro: {
    speaker: 'Putri Lilith si Vampir Cilik',
    speakerTitle: 'Pewaris Takhta Kastil Drakula',
    mood: 'mysterious',
    text: 'Ara? Manusia hidup berani menginjakkan kaki di ruang takhta kastil? Kau beruntung aku baru saja kenyang meminum sirup delima!',
    options: [
      { text: 'Apakah engkau keturunan langsung sang Raja Vampir?', nextId: 'lilith_royal', icon: '👑' },
      { text: 'Apa yang kau lakukan di dekat takhta kosong ini?', nextId: 'lilith_throne', icon: '🦇' },
      { text: 'Berikan aku hadiah bangsawan vampir.', nextId: 'lilith_amulet', action: 'vampire_gift', icon: '🍷' },
    ],
  },
  lilith_royal: {
    speaker: 'Putri Lilith si Vampir Cilik',
    speakerTitle: 'Pewaris Takhta Kastil Drakula',
    mood: 'mysterious',
    text: 'Tentu saja! Namaku Lilith von Ravencrest! Kakek buyutku adalah penguasa seluruh tanah ini sebelum para inkuisitor serakah mengacaukan istana kami.',
    options: [{ text: 'Gadis vampir yang sombong namun bangsawan.' }],
  },
  lilith_throne: {
    speaker: 'Putri Lilith si Vampir Cilik',
    speakerTitle: 'Pewaris Takhta Kastil Drakula',
    mood: 'normal',
    text: 'Aku bosan bersembunyi di dalam peti peti mati. Dunia manusia jauh lebih berisik dan menarik! Lagipula, Lord Malakar itu menyebalkan dan berbau busuk!',
    options: [{ text: 'Bahkan vampir pun membenci Lord Malakar...' }],
  },
  lilith_amulet: {
    speaker: 'Putri Lilith si Vampir Cilik',
    speakerTitle: 'Pewaris Takhta Kastil Drakula',
    mood: 'mysterious',
    text: 'Amulet Tetes Darah Abadi (+12 ATK, +20 HP) ada di brankas takhta kakekku. Ambil saja jika kau berani mengalahkan monster bayangan yang menjaganya!',
    options: [{ text: 'Tantanganmu kuterima, Tuan Putri!' }],
  },
  // 13. CELESTINE SANG ASTROLOG MALAM
  celestine_intro: {
    speaker: 'Celestine sang Astrolog Malam',
    speakerTitle: 'Penyihir Bintang Astral',
    mood: 'poetic',
    affiliation: 'Ordo Konstelasi Lilac',
    text: 'Selamat datang di puncak Observatorium Lilac, pejuang berdarah hangat... Konstelasi bintang malam ini memperingatkan bahaya besar di dasar Jurang Abyss Purba.',
    options: [
      { text: 'Apa rahasia bintang-bintang tentang gerhana bulan darah ini?', nextId: 'celestine_lore', icon: '✨' },
      { text: 'Berikan aku berkat cahaya bintang astral!', nextId: 'celestine_blessing', action: 'astral_blessing', icon: '🔮' },
      { text: 'Bagaimana cara menembus jurang abyss di sebelah timur?', nextId: 'celestine_abyss', icon: '🌌' },
    ],
  },
  celestine_lore: {
    speaker: 'Celestine sang Astrolog Malam',
    speakerTitle: 'Penyihir Bintang Astral',
    mood: 'mysterious',
    affiliation: 'Ordo Konstelasi Lilac',
    text: 'Bulan Darah adalah gerhana kutukan yang dipicu oleh altar kegelapan Lord Malakar. Bila engkau membawa Tongkat Bintang dan Bilah Nether Abyss, kekuatan kegelapan akan buyar seketika.',
    options: [{ text: 'Aku akan mengumpulkan pusaka itu!' }],
  },
  celestine_blessing: {
    speaker: 'Celestine sang Astrolog Malam',
    speakerTitle: 'Penyihir Bintang Astral',
    mood: 'holy',
    affiliation: 'Ordo Konstelasi Lilac',
    text: '"Bintang-bintang abadi, limpahkan kehangatan kosmik kepada jiwa pejuang ini..." Cahaya ungu lilak meresap ke nadimu. HP pulih dan batas daya tahanmu bertambah!',
    options: [{ text: 'Terima kasih, Astrolog Celestine.' }],
  },
  celestine_abyss: {
    speaker: 'Celestine sang Astrolog Malam',
    speakerTitle: 'Penyihir Bintang Astral',
    mood: 'serious',
    affiliation: 'Ordo Konstelasi Lilac',
    text: 'Di dasar Jurang Nether Abyss bersemayam Bayangan Void Purba. Pakailah zirah berdaya tahan tinggi dan jangan biarkan racun kegelapan menjebak langkahmu.',
    options: [{ text: 'Aku akan sangat waspada.' }],
  },
  // 14. MORRIGAN RATU GAGAK HUTAN
  morrigan_intro: {
    speaker: 'Morrigan Ratu Gagak Hutan',
    speakerTitle: 'Penyihir Bayangan & Penutur Gagak',
    mood: 'mysterious',
    affiliation: 'Klan Rawa Terkutuk',
    text: 'Kawk... Kawk... Kawanan gagakku berbisik bahwa seorang pemburu gagah berani telah melangkahi sarang rawa beracun. Ada apa gerangan mencariku, manusia fana?',
    options: [
      { text: 'Ajarkan aku trik bergerak secepat bayangan gagak.', nextId: 'morrigan_charm', action: 'crow_charm', icon: '🪶' },
      { text: 'Siapa sebenarnya penguasa sejati rawa ini?', nextId: 'morrigan_swamp_lore', icon: '🌑' },
      { text: 'Hanya melintas, ratu burung hitam.', nextId: 'morrigan_bye', icon: '🚪' },
    ],
  },
  morrigan_charm: {
    speaker: 'Morrigan Ratu Gagak Hutan',
    speakerTitle: 'Penyihir Bayangan & Penutur Gagak',
    mood: 'mysterious',
    affiliation: 'Klan Rawa Terkutuk',
    text: 'Ambillah Jimat Bulu Gagak ini (+35 SPD, +8 ATK). Bulu ini akan membuat langkahmu seringan kepakan sayap di malam hari!',
    options: [{ text: 'Langkah kakiku terasa begitu ringan dan lincah!' }],
  },
  morrigan_swamp_lore: {
    speaker: 'Morrigan Ratu Gagak Hutan',
    speakerTitle: 'Penyihir Bayangan & Penutur Gagak',
    mood: 'eerie',
    affiliation: 'Klan Rawa Terkutuk',
    text: 'Ksatria Godfrey dulu tewas dikhianati di kubangan ini. Jika engkau menemukan altarnya, sampaikan bahwa pohon-pohon willow di sini masih mengingat namanya.',
    options: [{ text: 'Akan kusampaikan pesannya pada arwahnya.' }],
  },
  morrigan_bye: {
    speaker: 'Morrigan Ratu Gagak Hutan',
    speakerTitle: 'Penyihir Bayangan & Penutur Gagak',
    mood: 'mysterious',
    affiliation: 'Klan Rawa Terkutuk',
    text: 'Terbanglah bebas, pemburu... tapi ingat, mata gagakku mengawasimu dari atas pepohonan mati.',
  },
  // 15. NOEL PENJAGA GERBANG BESI
  noel_intro: {
    speaker: 'Noel sang Penjaga Gerbang',
    speakerTitle: 'Squire Muda Penjaga Batas',
    mood: 'serious',
    affiliation: 'Prajurit Pengawal Biara',
    text: 'Tahan senjatamu! Wilayah di depan adalah Gerbang Reruntuhan Biara yang dipenuhi gerombolan Ghoul pemakan daging! Apakah engkau yakin ingin melintas?',
    options: [
      { text: 'Aku datang untuk menumpas mereka semua, Noel!', nextId: 'noel_courage', icon: '⚔️' },
      { text: 'Beri aku petunjuk mengenai tata letak reruntuhan ini.', nextId: 'noel_advice', icon: '🗺️' },
      { text: 'Tetap berjaga di posmu, kawan.', nextId: 'noel_bye', icon: '🛡️' },
    ],
  },
  noel_courage: {
    speaker: 'Noel sang Penjaga Gerbang',
    speakerTitle: 'Squire Muda Penjaga Batas',
    mood: 'holy',
    affiliation: 'Prajurit Pengawal Biara',
    text: 'Semangat yang membara! Ambillah salep perban ini untuk menutup luka-lukamu saat bertarung melawan para ghoul!',
    options: [{ text: 'Terima kasih atas bantuanmu, Noel!' }],
  },
  noel_advice: {
    speaker: 'Noel sang Penjaga Gerbang',
    speakerTitle: 'Squire Muda Penjaga Batas',
    mood: 'serious',
    affiliation: 'Prajurit Pengawal Biara',
    text: 'Di sebelah timur gerbang terbentang Lembah Tulang Purba. Bila kau terus ke selatan, kau akan mencapai sarang rahasia Lord Malakar dan Kastil Takhta Drakula!',
    options: [{ text: 'Petunjuk yang sangat berharga!' }],
  },
  noel_bye: {
    speaker: 'Noel sang Penjaga Gerbang',
    speakerTitle: 'Squire Muda Penjaga Batas',
    mood: 'normal',
    affiliation: 'Prajurit Pengawal Biara',
    text: 'Hati-hati! Bila kau terdesak, mundurlah kembali ke desa Ravenfall untuk memulihkan diri!',
  },
  // 16. ELENA SANG TABIB DESA
  elena_intro: {
    speaker: 'Elena sang Tabib Desa',
    speakerTitle: 'Peramu Herbal Ravenfall',
    mood: 'holy',
    affiliation: 'Warga Penyintas Ravenfall',
    text: 'Selamat datang kembali di desa, pemburu... Ya ampun, bajumu robek dan berbau darah! Mari kubasuh luka-lukamu dengan ramuan ekstrak kelopak mawar.',
    options: [
      { text: 'Tolong sembuhkan seluruh luka tubuhku, Elena.', nextId: 'elena_heal', action: 'village_cure', icon: '💖' },
      { text: 'Apakah engkau menjual obat-obatan herbal?', nextId: 'elena_herbs', icon: '🌿' },
      { text: 'Terima kasih telah merawat warga desa ini.', nextId: 'elena_thanks', icon: '🌸' },
    ],
  },
  elena_heal: {
    speaker: 'Elena sang Tabib Desa',
    speakerTitle: 'Peramu Herbal Ravenfall',
    mood: 'holy',
    affiliation: 'Warga Penyintas Ravenfall',
    text: 'Rasakan kesejukan salep ini... Rasa sakitmu perlahan mereda dan staminamu kembali bugar seperti semula!',
    options: [{ text: 'Tubuhku terasa segar kembali!' }],
  },
  elena_herbs: {
    speaker: 'Elena sang Tabib Desa',
    speakerTitle: 'Peramu Herbal Ravenfall',
    mood: 'normal',
    affiliation: 'Warga Penyintas Ravenfall',
    text: 'Aku mencampurkan ramuan dari bunga mawar gotik dan embun pagi. Ramuan ini mampu menangkal racun rawa dan memulihkan darah secara cepat.',
    options: [{ text: 'Ramuan yang sangat berharga.' }],
  },
  elena_thanks: {
    speaker: 'Elena sang Tabib Desa',
    speakerTitle: 'Peramu Herbal Ravenfall',
    mood: 'holy',
    affiliation: 'Warga Penyintas Ravenfall',
    text: 'Selama para pemburu seperti Anda berjuang di luar sana, kami warga desa akan selalu menjaga api lilin tetap menyala.',
  },
  // 17. VLADIMIR SANG PELAYAN KASTIL
  vladimir_intro: {
    speaker: 'Vladimir sang Pelayan Kastil',
    speakerTitle: 'Kepala Pelayan Istana Drakula',
    mood: 'serious',
    affiliation: 'Keluarga Kerajaan Darah Abadi',
    text: 'Selamat malam yang dingin, tuan pengembara. Saya adalah pelayan yang merawat kebun bunga mawar hitam ini. Harap jangan merusak kelopak mawar berharga Yang Mulia.',
    options: [
      { text: 'Siapa yang menanam mawar hitam berduri darah ini?', nextId: 'vladimir_roses', icon: '🌹' },
      { text: 'Tunjukkan padaku pusaka bangsawan yang tersimpan di sini.', nextId: 'vladimir_relic', icon: '🗡️' },
      { text: 'Aku hanya mengagumi keindahan taman ini.', nextId: 'vladimir_bye', icon: '🍷' },
    ],
  },
  vladimir_roses: {
    speaker: 'Vladimir sang Pelayan Kastil',
    speakerTitle: 'Kepala Pelayan Istana Drakula',
    mood: 'mysterious',
    affiliation: 'Keluarga Kerajaan Darah Abadi',
    text: 'Mawar ini disiram langsung dengan intisari embun darah murni para bangsawan vampir terdahulu. Kelopaknya tidak akan pernah layu selama gerhana bulan darah bertahan.',
    options: [{ text: 'Bunga yang sungguh mistis.' }],
  },
  vladimir_relic: {
    speaker: 'Vladimir sang Pelayan Kastil',
    speakerTitle: 'Kepala Pelayan Istana Drakula',
    mood: 'mysterious',
    affiliation: 'Keluarga Kerajaan Darah Abadi',
    text: 'Di dalam peti berbeludru merah di ujung paviliun tersimpan Rapier Mawar Hitam (+22 ATK, +10 SPD, +4 DEF). Hanya mereka yang berjiwa ksatria berhak mencabutnya.',
    options: [{ text: 'Akan kubuktikan kelayakanku!' }],
  },
  vladimir_bye: {
    speaker: 'Vladimir sang Pelayan Kastil',
    speakerTitle: 'Kepala Pelayan Istana Drakula',
    mood: 'serious',
    affiliation: 'Keluarga Kerajaan Darah Abadi',
    text: 'Semoga malam Anda menyenangkan, pemburu. Dan waspadalah terhadap aroma manis mawar yang memabukkan akal sehat.',
  },
  lord_malakar_boss_intro: {
    speaker: 'Lord Malakar',
    speakerTitle: 'Penguasa Tertinggi Gerhana 100 Lantai',
    mood: 'eerie',
    affiliation: 'Tentara Mayat Hidup Gerhana',
    text: 'Akhirnya... langkah kaki berzirah putih itu mencapai puncak keabadian yang sunyi ini. Ratusan tahun kucari jiwa yang cukup berani mendaki menara kutukan ini, Ksatria Fana. Engkau mengira darah para penjagaku dapat menyelamatkan desamu? Bodoh! Di hadapan Takhta Gerhana ini, segala cahaya hanyalah ilusi, dan jiwamu akan menjadi piala keabadianku yang berikutnya. Bersiaplah binasa dalam kehampaan abadi!',
    options: [
      { text: 'Pedang suci ku takkan gentar oleh kutukanmu, Malakar!', action: 'close_dialogue', icon: '⚔️' },
      { text: 'Aku datang untuk merebut kembali takhta Ravenfall!', action: 'close_dialogue', icon: '🔥' },
    ],
  },
  blessing_not_ready: {
    speaker: 'Suster Genevieve',
    speakerTitle: 'Pelayan Katedral Suci',
    mood: 'grumpy',
    affiliation: 'Ordo Salib Perak',
    text: 'Jiwa dan zirahmu belum cukup matang untuk menanggung berkat suci ini. Tingkatkan levelmu lebih tinggi lagi untuk menyerap energi suci Katedral!',
    options: [
      { text: 'Aku akan kembali setelah berlatih lebih keras.', action: 'close_dialogue', icon: '🛡️' },
    ],
  },
  astral_blessing_not_ready: {
    speaker: 'Celestine',
    speakerTitle: 'Peramal Astral Bintang Malam',
    mood: 'mysterious',
    affiliation: 'Observatorium Langit Malam',
    text: 'Konstelasi bintang astral belum menyetujui penambahan kekuatanmu saat ini. Kumpulkan lebih banyak pengalaman tempur dan tingkatkan levelmu!',
    options: [
      { text: 'Baiklah, aku akan mendaki menara dan bertarung lebih giat.', action: 'close_dialogue', icon: '✨' },
    ],
  },
};
